import type {
  MediaKind,
  MediaModelMode,
  MediaOperationConfig,
  MediaRequestFormat,
} from '../../types/provider.ts';

type MediaConnectivityOperation = Pick<
  MediaOperationConfig,
  | 'name'
  | 'capability'
  | 'method'
  | 'path'
  | 'requestFormat'
  | 'modelMode'
  | 'model'
  | 'testRequest'
> & {
  // Form-only fields let the editor test unsaved operation overrides.
  testRequestJson?: string;
  testRequestMultipartFieldsText?: string;
};

export interface MediaConnectivityRequestInput {
  kind: MediaKind;
  baseUrl: string;
  model?: string;
  operation?: MediaConnectivityOperation;
  headers?: Record<string, string>;
  apiKey?: string;
  apiKeyHeader?: string;
  apiKeyPrefix?: string;
  authIndex?: string;
}

export interface MediaConnectivityRequest {
  method: string;
  url: string;
  header: Record<string, string>;
  data?: string;
  dataBase64?: string;
}

export const MEDIA_CONNECTIVITY_TIMEOUT_MS = 65_000;

const CONNECTIVITY_BOUNDARY = '----CPA-Media-Connectivity-Test-7f3a';
const CONNECTIVITY_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
const CONNECTIVITY_PNG_DATA_URL = `data:image/png;base64,${CONNECTIVITY_PNG_BASE64}`;
const CONNECTIVITY_IMAGE_PROMPT = 'A simple blue circle centered on a plain white background';

const defaultPathByKind: Record<MediaKind, string> = {
  image: '/v1/images/generations',
  video: '/v1/videos',
  audio: '/v1/audio/speech',
};

const normalizeBaseUrl = (value: string): string => value.trim().replace(/\/+$/, '');

const expandModelPath = (path: string, model: string): string => {
  if (!path.includes('{model}')) return path;
  const encodedModel = model
    .trim()
    .split('/')
    .map((segment) => encodeURIComponent(segment))
    .join('/');
  return path.replace(/{model}/g, encodedModel);
};

const joinPath = (baseUrl: string, path: string): string => {
  const base = normalizeBaseUrl(baseUrl);
  const normalizedPath = path.trim().startsWith('/') ? path.trim() : `/${path.trim()}`;
  if (/\/v1$/i.test(base) && /^\/v1\//i.test(normalizedPath)) {
    return `${base}${normalizedPath.slice(3)}`;
  }
  return `${base}${normalizedPath}`;
};

const hasHeader = (headers: Record<string, string>, name: string): boolean =>
  Object.keys(headers).some((key) => key.toLowerCase() === name.toLowerCase());

const setHeader = (headers: Record<string, string>, name: string, value: string): void => {
  const existing = Object.keys(headers).find((key) => key.toLowerCase() === name.toLowerCase());
  headers[existing ?? name] = value;
};

const textBytes = (value: string): Uint8Array => new TextEncoder().encode(value);

const decodeBase64 = (value: string): Uint8Array => {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return bytes;
};

const concatBytes = (...parts: Uint8Array[]): Uint8Array => {
  const length = parts.reduce((total, part) => total + part.length, 0);
  const result = new Uint8Array(length);
  let offset = 0;
  parts.forEach((part) => {
    result.set(part, offset);
    offset += part.length;
  });
  return result;
};

const CONNECTIVITY_WAV_BASE64 =
  'UklGRkbIAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAATElTVBoAAABJTkZPSVNGVA4AAABMYXZmNjAuMTYuMTAwAGRhdGEA' +
  'yAAA/P/8//v/+v/6//v//P/8//7//v/+//7/AAAAAAEAAQAAAAAAAAAAAP//AAABAAEAAAD/////AAAAAAEAAwADAAMAAQACAAEA' +
  'AAD///3//v/+//////////////8BAAAAAAADAAIAAgAEAAMAAwADAAUABgAGAAcACAAKAAcABwAFAAYABgAFAAUAAwADAAIAAQAB' +
  'AAQABQAFAAUAAgADAAUACAAHAAUAAgACAAMAAQD//wEAAgADAAIAAwACAAIAAQABAAMABwAHAAgACgAMAAsACgALAAsACgAMAAwA' +
  'DAANAA4ADgAMAAwADQALAAsACgAJAAoABwAHAAgACAAEAAMABwAGAAcABgAFAAQAAgABAAIAAQD//wAAAQD///7/+v/5//r/9v/2' +
  '//X/9f/1//P/8//y//L/8v/y//X/9f/2//b/9P/y//P/9f/3//j/+P/0/+//7P/q/+r/7f/t/+//7v/v/+//7P/o/+T/5v/m/+X/' +
  '4//l/+P/4//l/+b/5f/k/+X/5v/n/+P/5v/q/+3/7f/p/+n/7f/w//D/7//x//T/8//x//P/8//0//j/9f/5//z/+f/2//f//f/6' +
  '//3///8BAAUACQALAAwAEQASABUAGAAWAB8AIgAeACEAIgAfACIAJwApACUAKwAoACkAMQAvAC0ALQAxADcAOAA2ADQAOAA0ADMA' +
  'OQAzADAAMAAuADIALgAuADIANQAwAC0ANQA0ADAALAAvADMAMgAxADQANgAxAC8ALgAyADUAMAAxADEAMAAqACgALQApACkAKwAo' +
  'ACQAIgAiABwAGAAXABUAFgAQABAAEgAPAAwADAARAAsABAALAAoABAADAP3///8CAPn/9v/8//T/7f/w//H/6P/t//D/9P/w/9n/' +
  '+v8KAO7/8P8CAAAA8f/4/wMA/v/6/wEACgAKAAQABgALAA0AEQATABUAFAAcABcAGAAcAB0AHwAdACMAJQAdAB0AHQAhACEAIAAj' +
  'ACgAJgAcABoAFwARAA8ACgALAAcABgAJAAIADAAPAAsADQALAA4AEAAPAAIACwALAP7//P8BAPz/9f/6//n/8P/y//L/8v/u/+3/' +
  '5v/i/+X/2v/V/93/1f/J/8n/0P/K/77/w//I/8L/uv++/8f/vv+5/8L/yP/F/8j/zf/M/8//0//Y/97/3//k/+r/7P/v//X/9//1' +
  '//v/AQAGAAIABgALAAsADQARABAAEQAZABgAFQAcACAAHgAbACEAJAAeAB8AKQAtACIAIQAvACsAIwAmAC4ALAAmACoALgAtAC0A' +
  'MAA3ADMANQA7ADkAOAA2ADcAOAA2ADcAOQA7ADsAOQA5ADYANQAxACoAJQAgABgAEQAKAAAA8//o/+L/0v/N/8v/wv/F/7v/t/+4' +
  '/7n/uf+2/7j/sf+y/7L/r/+u/6v/rf+w/7T/uP+5/7n/wP/E/8T/xf/I/8v/xf/J/8j/xv/H/8X/x//G/8b/x//E/8j/zf/O/8//' +
  '1f/d/+D/4v/o/+//8f/2////BgAJAA4AFgAaABsAHwAlACYAKQAsACwALQAtAC4ALwAxADEAMAA0ADQAOQA8AEQASwBQAFcAXgBn' +
  'AHAAcwB2AH4AgQCEAIcAiQCNAI0AjwCUAJkAngCfAKYArQCxALYAvADCAMYAyADKANAAzQDJAMoAywDEAMQAwQC0ALEArgCmAKQA' +
  'nwCjAKEAngChAJ4AnwCdAJgAlwCUAJEAjACJAIcAgAB8AHYAdgB0AG4AcwB3AHYAdAB1AHYAdQBwAGkAYwBYAEwAQQA3ACcAHgAZ' +
  'ABIADgAPABMADgAMAA4ADgALAAcA/f/3/+z/4f/X/8z/wv+2/6//qP+n/6f/p/+w/7T/wP/L/9D/3v/u//b/+/8JAAkACgAUACAA' +
  'JgAnADIAOwA+ADwAQgBGAEIARABKAEgAQgBJAEsARwBLAEsAVwBbAFkAYQBmAG8AbwBrAG8AdQByAHQAegB6AHkAdwB5AHgAfACH' +
  'AH0AdwBvAGwAcwBhAGYAWABbAFkAWwBRAE4AVQBJAE0ASQBTAE0AUwBVAGEAaABqAHUAdQB9AHEAsABpAPQAGQCXAYH/swbfBJkB' +
  'of5F/jIBhP/JAE7/3AIRAN//dAB5AwMAfv/tBHABYAF9AJcCDf+j/18AMgMp/3X/UgLy/wz+gP/k/yIBjf2PASn/EQCS/fEAff07' +
  'AcoAxfsrAAoBNf5i/TEAwwIA/mf/7/3dAl39nPzlAkL/OPuTAX3+BwFj/K8Czf37/8n8kv5qATYAlf3j/j4CYv/X/OoAJQQP+sP+' +
  'Xv8eAhH/evt7AFcCdfqPAyj8BAKc/kr/0ALq+zT6dAjc/Rf55QESCEf11v4XBBIDavCnCV0CwveSA38EPfYP/48Jafqx+EwIyACi' +
  '8ssEQAWe/Wr4TQgIBunwtg2Y/8v5WwXvAen6Kf4/DfXxp/6iDUb4a/w5CRgABPdmA9wAKf26AT78hwbM+Y3+4Qb+/1D8JgCeCtn1' +
  'Jv2ZCqb8u/IbEFX+O+7WClYGEPOMAH4J0/vO/GsHDv7m/WAHy/YgAXIIvPsd+50FnAFi+gsDRP+D/5cCIf1P+7UHqfyp+4EBsQC8' +
  '/p36mAW+AHL75ADKBC3/5fq0BCwAU/x3Aqb/j/1N/qsCfvwx/roBV/xd/R8AtP15+84CTv3I++0DhAAO/HYBawcD/YH/kAda/+QA' +
  '4gLwAkX+jP3ZATX4XfpW+5L1Y/Ut+0731vZg/QIAfQA6AuEMgAebDTgTTg5iEMoOAwy0A4cACvxm8KzqUuZu3BncROFw3/zkU/Yl' +
  '/n0Johq7Jd8pPC/qMgIuviSoIFIPCQF08j7fFNofw4LBOdUkxAHaJeiq+p0HdhV7Le0orDU5N8EwhCxeIOca5QywBkH7nO/V5Svc' +
  'TNhmwzTdgtie2p/vOPnmBr0HBiE9IAUg2iwcJhMloR1FG/4R1wqWCkj9nPkq7mTfeeKkxbDX99+b04rvz/LYBWAIkhWKIjUbQSjo' +
  'I/seFx/UEvcStwpaCAcEIvu7+WPin+Yf0WDJK+cyzt/ppfEQ/+0LZQ4jIkEcriCOJ1Ua2R+oEUIQ/AwKBocHtv3V/SfvouC44CDD' +
  'quBK1+rZQfVK9xULHAsEGu8gJBeQJoMb6Rr2FuQL3BFHBz0InwWM/ev6wuHl4/rIpc/W38vOu/D2874GcA1tEykjeRfoIPgejRiM' +
  'GgkLcBH4C38HswlpAoL/4unn4YzWGr/f48TMAeQr9hb9PxLxDnAfYR3/GSMiIhYBHJcPiwyGER4IAwsFByIBLfWJ4aDcub0a3PLR' +
  'ktZS9hX3ZhBhD1gblyGAFtwhJBjuGZYUigiDFHMJ+QkIDDQBnP9h48viv8YAyUXgwMlB8vnyqQm5ErcTlyN/GOMcSx1WFbYZxgg8' +
  'EYYOKwneDJkFhwNb7ULhjdN+v4Ld/8zE40j05P9BEwkStB+qHJUYoR8SFDgayg0RDLYSZAmoDVQKUAPK+eThcN2lwCPRmdgU0h3z' +
  'DfhIDlwSQBigIXwYxxzWGo4UNhiqB2sS2Q5rCssPbwTdAKvqJ9w2zgvBldv9zH3o7/QJBUYSpRZVH9gepBnUHp0XIxfWDyIN5xE5' +
  'C+cLQgvJ/2D2Jt771XfAINSW0cnY+POf+xsOohQKHJggcRrAHkgbIxjqE5QNZREODkkKSQ74AUX6nOow1RPL/Mb31kLPuemH9mUE' +
  'ThEpGTMfZh9lHaQgzRqkGBkR5Q+GEF4K9wpmCHH5EfRL3pvRSMRr09nTZdil8Wb8xwiPFJoaFCCnH2MfxCAFGyIZAw95EXsNZwfb' +
  'Cp/9rvgJ6frXXszoyufWBM/y573yLACkC10XHBwBIdQeFCVTIJcdQBaYEioRsglOB50EAPe58WzgaNU/x6nUMtQQ1/ftyvXfBJsP' +
  'zhZJH8kf+CKHI50h/xvsFIkTUA1dB/kGyPwp93Tr799o0NXNL9kz0G/i9uvT+0MEKw8+GWgdLR9AJP0i0iLDGS4XbhQdC1QIrgOg' +
  '+6HzC+qe3o3P59M42XvSPeQc7q/6QQIIECkWAR45HYImRiKUJIoZrhklE+8KYwZsApb4nPMY6oDgFdKS2AXb4dPM5afsVvms/+wN' +
  '9BNjGKUeyyLNIK0itRrHGNsS2wqJBwICvvtg9+/uCuan3d/VPN6q2SHfqulj9O75fQa1DUkVZhoCIVAfxSF3ILEYbxVMEKUHXAQP' +
  'AHn4LPTk7fvkHNpX32LhjNv15GTva/UW+yoJsgytE9QZWR3aHEghrRjZGPMRmgwiB30E8P5M/HT2I+8c6hbj6d+A5DniTOU47Vb1' +
  'uPhfAQwKDw81FAgaixgqHHsayxROEVIOiwkKBUMB/P/m9lr32PAP6DXoy+Xd5/nlNu/L8D72af6fAikHGg9lEPUT8xg/FTASaRdB' +
  'DN0GdQqABvT8dwMx+aj04fUX8gvqqe006e7zYu9q82712/9v+9IDTA4GDIgLERVLD6ALlQ8tDyIIyfo3FD8Fx+4QAKMND+mE74cB' +
  '2/EV6af+Du7j9k4BUPig9kAOPwCk/HgS/Q4Z++IOHxPKAigBZRKpAdgB/AX5+EwE9v/y5s8LswKi3NcDhwp05nz9pgmU9Dn5iAmK' +
  'Boj0tgmsDiv8k/pMHH36L/7BDiIFpvi7BqwGBfob+40FIfMDDUjzP/icAUkFGeywBcoDQfe0/D0QpPVe/LMPugGY7+wSuAnD9IX8' +
  'Mhaj/JbxHxBIB5fuugNaENnzl/CzFPEAjeY/C8IKqe8i/UIOp/fZ/XUH4AYn9NABFRBU+37zExIQCpPm2RTuBdXvcAytBK7o9xR2' +
  'A4XnuQmIDZfwOPxLC6D9Z/t3B3r7+ALQAfAAZfiFD8P6uvkUDdIDiPE0Dr4Axvh8A+sDDPShBfcFv+8zCOQKdfBO/Z8SofaJ9R8Q' +
  'KQCh8xsIfwJSAvD1xAoV/7H8zACcDJ7sMAxPBe/0MfkhGdjrWvvCDWEEM+yoCWUNDPWp9cEQw/0u9yMAiwyD9er7xAOHBvn2WfzL' +
  'BjgCDPeCAyQHGPN8BRkIIPMX/h4S5/i983YOcwIQ8TsIUwcm7awHIgXM9e/7qgph+/L5uQKQACb/0/+0/DwElgMV9QUHngMx/rb6' +
  'bgju/Zv8nf2MDcPvW/0+CrQB5u6MA7kPOu90958W0vKw9EIQ1/s29qgIVQNB9EgFCwcb+xv3JQ8p/1bzxwVxBHn7tvs3BPYAD/q7' +
  '+6IMrfOX+tEM/Pti8TIPbgPH60cI2xD57Qb8XQ30AybsQQjUDDj02fRjFgL5oPA0EFEEo+T7ErgEYO0ZAsURzuvOAUgL5vf5+ekM' +
  '4PtA99cJ+f6p+DkIEwBs9r0InwO89MoFjgQX98wAjgAFAur8HP1u/1MGtvky/ZIJKvsi+KUKIvx0/FoBfQEJABX/LvtsCAL7Jf31' +
  'ALQGH/TlAcYGRfvp+u4GZwAV9coH9wYt9ND65BO2+SHrFRRLBhHpmgXnEIPupvvDFBnxWvcMEy77wOtPGGP41PTkCXMCu/dqCHD3' +
  'awCPCoH4MPtYBu0DjvgNAFkEof4q+UsH7AIl8R0JyAkq6joIkQ1s8kb8XweSCgTuEwDfEXb1ZvXeD9QC3fKQ/6oVEu8U9sAVNv1E' +
  '6S0Wxf8e8ToE9gsh9MP+dwud+C/9Qgex/mH+2AJ9+xUIKvxo+vEIYP/l+OQF+AFx+zT7iwu3+iP2lw/M+0H00w5UBx3pzAxcD4jr' +
  '0vmNHMb0iu1MFMUH/eVcEFIJdPH7/WcOGvrv9yIDCg5s8jD3BxbY/LTrnA1zC0TwlwAiCQMAZAAj+3H++BHQ7tD6Sxd883jzBxKJ' +
  'AMzxEwd+Bff4z/wVBvv/Rf0H/LYJoPz082gPtAS47ScILA4E8yX4xhBxANPu5QV+E1rrsPpmGavzGvIKEu8BwOoHCi4Pn+pl/GgU' +
  'NPx+7UsOGA796T0AGhV38gHzTRnd+xPrkRHjCXDq8wjbC672j/uMCCMEJvYaA5sJd/Wm/UANKfk/+dQImgS2+HMA7gUi/8H7qgFa' +
  'ByH/WfhkClwFyfNUBVgH8vjhAm4ArP+XAND9UQE6BGX57ADfAcn/r/oOAAYDF/1n/TEC9wWB+Q//WQVIBcT27QNvC5L2pv1HD0f6' +
  'FPZ3CywGevMG/+gMM/pD8roIvAWf7U79VA1W9Rv4hgjhAf36OQHlCXABEwDjCxwFG//HCQMHBPz3BqYAsvm8ADH9YfYl9xP8IPXi' +
  '89v8YPbq+dIBWv2RAdYKtgYmCCoSeg8mCosSsw0iAwAI2Ael+l72ZP2T8tvoNe1x7Jvo9e3N71zzZPpLAacE8Ql/EugWchXXGZcc' +
  'pRY4FHsTrwy4BSoEEP5A9Tvyx+uy487iEeii5uHl2O4n9wD3CQFgDhcMcw12G7UYzhKLGfAXPhEtEaUSewvHBi4ImAEt+Tr0ju5H' +
  '4I7hjeNV3U7ik+tc7yn13AEVCQ8N1hPFGqQYkhZ+Gd4UuQ8CD2gPXQpaCrQKOAYaAI77lvSf6e/cROK83kDZKOGY6tru1/biBUAN' +
  'hxHlGMMeyhczGuYXLQ+mDSQMuAvkBpoLJQq8CCcEX//g9AjtQN3c3Lreudgk23jn9u/89KgE9A8gFUQaoh8gHlgXEhZ9EOUIDgeh' +
  'CqUFvgfsDDgLHwhYBRL6P/D04yXZ0NtN2LfYEt9I7Xv0aQAcDVYYeRtiH2sh6BgyFWQQDAolA2kGoghjBhcLYxCkDRQJ8APY9lfq' +
  'f9qE2r7Yk9Tx2B/mQfCR+HQIXRSjGmUdriEhHQQWNBHmDLYC7gJ/BhIGXAfNDswR8gxjC0QCCvO85yjZ3dhU1lbX6NrQ6JjzU/1k' +
  'C70WqhxBHdYfmxsHEhoOLQkNAav/9gWABjoHEBCxE8MOuQtmBY7zUOeO2pvXd9Ub1hPanOZw8zz9kwoJF3Md2x22HiMdehJXDS4J' +
  '2wGM/B4DgwUrBUoNMhSPEAQNWAmf+UrrxN5a2hnXy9QP2b3ibO/d+JoG5BI6HIYd9h5+HnoVHw4gCxYEjfts/0MEVQNrCBgSpBIk' +
  'DpEORAPW8eXmENx42LvU7NbN2+PoV/NYACoNTBiDHXcfAx9qG74QEw3RBkb+KftQALQBHwPkCwQSBBGOD+sMQPzN7+3jK9tm1vnU' +
  'HNhh3u7q8fVwA/APORpBH6AgtB8CGG0R+AovBH/8Lvvy/oD/XgSaC5URURHUEOYLQ/zO8Cvk+NmU1q3V4tZj3fXrRPUcAoMQPhu5' +
  'HgciTCDpGa0Q9wweBI38zfvc/dv+iwJ4C2EP9RCHDzsNAP6i8r/ma9uh1xLW6teC2zXpcvKRABENyhiYHcEhUCB1G30S8w5jBoD+' +
  'Df1t/XX/EQK2CQMNoxB1D5MNowEA9hzrH98M2nXXNtgx2tfkL+6h+WgGCBJ1GSUd/iChGyQWHhOcDKIEOQL2AZP/gQIbB68KKAzo' +
  'DXYL8gQe+ojyNuXo3u/cmduW2vXgx+mz8Ir93wcIEfwVzRtLG3wYYBWQEowM/AZmBTIEEgRUBQcJrQkIC/UJkAaO/8f3GfGx5uPi' +
  'XOH236HgvuU77IHy0/yABZ4L3BBbFn4WWBUYFYIS3Q3GCsEIdgdfBngH7gcxCBoIPwdEA9r/0Pmx9ObuaOmd52rn6uYb6JnsLvAE' +
  '9838WQMDCPUMfA8oEeIRoRAgEG4NYgt0CeYIqwdDB2II+AaUBOwEjgGo/n77afgz87XwBe9I7nDs8u178BDypPUQ+j/+KAHsBTII' +
  '+Ah+CqQLqQtTCicKXQlvCMYH9AcqB7oFrwUtBEwCBQAW/cT7dvoT9z33C/WA9CH1/PR49qT3AfqX+ob9vf44ALsC5AKuAyAFEAa1' +
  'Be4EQQaiBkoGwQYLBt0EwQMFBB8BdgCDACj+//3O/Az90vvY/Ez8c/zl/fL83/0x/n39Df46/yb/4v4c/9n/qv+eAP8AtgIqAoYB' +
  'FgPiAqMBVQLiAcMA7wDhAfoAk/+LAIAAEwCdAPr/TgHe//D+Pf+r/xv+rf5p/lb9G/wj/vn8K/4E/pP+4/45/qz/WQBMAHj/yQHd' +
  'AKj/aAEHASoANADYALoAeAH6ADQAPQAeALD/RABV/0f9U/47/WP9Kf68/Xv8Nf7b/YD+1f6d/iYA/P8VAJf/YQC2/1EBbAAeALoB' +
  'RwDZALwA/QCSAYX/PQCqANv+L/9H/qr+Av38/qz+o/1j/hf/4v5r/gEAMQDE/1IAPv9eAAgASQAkAGMB8f/BAPAAiACBASABxgBZ' +
  'AFsABf9l/6z+Tf6I/+n+hf5T/i7/7/8j/90AFwA2ABoB6wAjAY8AnAEKAH8AQwB5AeQAtQCLAEkA5wB7AV0AsgBs/8r/7v8Y/6b/' +
  'VAC7/pr/DQAKAA4A6f9sAVYBCgHxABMCgwGIAHIBFgHAAOwBLQCCACwAywDHARwAggBo/0oAqv9F/24AvP+r/+3/+f7s/xAANAE8' +
  'AP3/AQFfALkA+wA7AUoAeAH4AI8A3wHkAMMApQCbACUBDwCQAJT/t/+C////xP9X/0sA8P///9T/MwDJ/2wAagG9/3kAFgB5AO3/' +
  'iAAuAfkAhAA+AcgAZwFyADUAAgEXAKoAaABg/wP/+f+k/+v+SQAMAAb/mv86ALb/wgAN/10Azv4aAKIAjgA7AGP/TAGPAGIAxv/4' +
  '/4kAOwA5AXD/MP+L/9//IADv/vn+mv6E/+z+/f8QAEf/Bv8RAL//7v4FAHMAmP/u/7f/G/+iAJf/qgCq/yAAyQCx/3UBRP96/7r/' +
  'M/8fAGn/Ff8V/4L+lf+3/0D/ewAuAJ7/9v4RAFj/2/8A/xEAPQDw/9T/OwBaACsAowDT/zMAmgAqAHUAmAB2/9H/RP9b/0v/1ABW' +
  'AFb/MQDJ/ygAvP+xAAMAsf9OAAX/JgD2/zQABgECAEUAywCSAJYB2wBZAMH/9v8tACYBzP81AMX/yP/2/mUAmgCyAFMAagAPAKv/' +
  'VQFNAAoAof8XAIQBxf+hAPf/2QDy/28A+wC0/zoBMwGZAG//kwAUAHn/YQAwAPj/B//K/zkAl/8UAUwAMwAEAA4BqwCT/5cAjQB6' +
  'AKcA7f9p/1UAFgALAWAACQFdAQsAMACXAE4ArQAiABoBy/54Aav/Tv8QATv/kv94ADsB5v/ZAAQA8QBrAEkBHgB9ANIAH//7/67/' +
  'nABIANgBaAEiAMAAMQBlAJ4ABQDX/2AAv/8nAKT//wBQ/zkB6AB/AD0A1P8KAAIAbQHZ/yMAZf+m/7cAyv+JAPD/av/xAHMB8f81' +
  'ATEApf9bANkACgBL/5oA+/8eATv/sAGe/2z/Vv+5/xUAOf8oAfX/9f/m/iwAdgBa/2YAiwDx/8r/QQGI/qz/LgBR/xf/yv9iAfb/' +
  '0gAHAAAAz/89AKv+6f9H/hwA4v9y/5MA9P/r/wL/uQAzAMH/nADSAKj+0P8gAGAAev+y/+r/rv5a/iMB+f4f/9P/wABIAIb+5AE1' +
  '/jT/NQDB///+pP4K/xgA1/6n/0AArP6W/58ARP9GADoAqwCV/8z9wgBG/4n/GgArAIX9//+5/nr/DAApAGIAOv84AQn+GAAoAS0B' +
  'vP/b/csAdP03/u7/OgAE/6sAnwBW/zUB7P+Y/nH/Zf7O/0D/V/92/z//Zv8t/jwCTwEBAisA6gCT/lz/zwE9ALD+nf+RAKP+rQD+' +
  '/pH/x/0Q/kIATv+v/77/GwGQ/84AdgLw/qj9SP7+/ur9sf4+AKT/0/2q/qD+u/40ACQAGAKm/n7/wP9j/7YAZADxAb3+mwCw/+H/' +
  'zv2NACoBZ/4HAID+4v3S/XkAyv5cALkAnP6E/9v+JADB/xkAFv/c/UIAkQCkAGMAMAG2/2wAGAI4AXwAmP9u/3H+jP1t/eT8J/3m' +
  '/Kv80v21/RL9Qv+v/0EB0AIxAwcExQNSBRcFpwZwBlAGbgTjASQAIf3D+vH2//Xm8j/wou7i7q7wU/OP+dL8+AN5CLwOkhKhFWwY' +
  '6xfSF6wUpRIaCk8D9f3696Lw0OmN3/bcA9713r3l5er58yz70wZPEMkWHxyDH/Uf8x3RHUgaBxaMEZMNWwZaAvn8Z/Sn7erd6t8m' +
  '2sPanuAJ5hHvqvTgBbILVRarHb0iuSITIjcisBnPFmERugwwB0oF1P5++kvzL+zO2jjbSt5x1z/j8ufD8TH1uwiEDxsWdCCQIr0h' +
  '/h2mH6kUYBPID/ELlghyBzMCifxO9wDvmt761Pbec9Mb3s/m3+/f9P8EMhLNEy8hpyKfIR4dfx0BFFcQ9g2SCUMH6AbPBIf+kv2d' +
  '8tPpJtMr3tvWtdWf5ZTpt/N/+vARYhCFHVok2iDqHh8cZRdsDlAPwAk7B2kHiwe5AJQB3/kr79Pda9MR34fOnN8r5truJfUQB8ES' +
  'FRPmI58gYB//G04akA/iDrYLOAZWB98GdAX3/iEDrvJt66/Wldf22mHQFOZv59Pz4fnLD6IQhhmNI7UcEh4VGqsVbg2mEIoHTghD' +
  'CNEGywIMAUX+Ru0i5xzPwNvp1GXVGul36xz3SAFwFGcQIiDgIIYckBwnGTgRIQ8FD6wFvgrFBrAGXwEeA0b3tOy833PNPuBBzgre' +
  'iemW74D5LgowFNwTLyXMHcQeeBz7F8gPwRL9Co0H7QrzBMEFz/9WAOnvJuuw0nTU49vuzGvouekr9N//VxLsEGwdUyMlHAkgxBoU' +
  'FTkRURObBlEMhAdPBSkE7v4/+8XrpeSFyp3c6dH31P3s2OqW+Y0HuBRXEgcloh+kHg0gVRn4EmEUQA70Bj4MywLQBef+XP778Qjr' +
  'ptSrzybepshW56HpCvFBAPMPQhFcHM0kPhyjInMbgxd+EucTuwcJC1YGfQNwAzH8k/ur64rj18q520TQDtU87YDosfqiB0gSRBPu' +
  'JC0dICAPINsYNxacFP4ORAg0DO8BdwXO/bX7cvHr527TEs0x3djH7eYI6ubw8AFeEPQQWB1LJe4ZyCRwGuQXWhS+E3QILQtXBuAA' +
  'ywJy+Wr4hOk84VLHC9tj0LzT0e/X6HP9KwmtE9gUPSdKHS8hxCG6F0kXOhQPDsMH0Apl/8sC0vru9xju1OQ+0NzNotz1yMfq4eqD' +
  '9J4GBhFXFH8gOSQxHJglwRnUGH8V/hHuCEMLTgM5AND/hvbE83fnrNpKx/3ePMu63NbvBeuAAloMwBNWGskneBzmJFsgpxjeGLoU' +
  'GwxFCpQHxP7xAPb31/QM6jDiE8g52kTTFNHR8KnnTvztCMcR+hWzJvgejSKoJAAbchqkF68PJwopCxj/sAH1+Zb1fu185THRNdBM' +
  '3c7JGesi6RfzcAaoDScUHSFDI/Ae9SbDHe8bCRrJExYMUAwMBA8Alf1p9YjwDOfC2QrL1d7ayzzfXux36tIBZAk6EQgbNiWcHRkn' +
  'QiItHa4dNBc2D+AMqgeI/1X/IfYT8lnpBeAWzKnbj9MV1IvtxOWx+kwFnQ02Ff0iHB8LI+omah5WII0bHxNDDiQLVgHc/ln5svKE' +
  '68vk29A51gDb/M1R6cPkM/Kl/9cIlA+jHCwgvh1hJ9IgiSDpH2wXpxFEDrIFFgBB/AP1me4w6EjapND338PNmN9Z5jTn1flEACgK' +
  'RRP2HlsaayRhJMAgUSR3HBAX7RGFCh4D4P7g9/fx2upG4zTTMduV1/rTAeaI4drvTfh+AhYKABe3GXocpyVOIfUkMyMtHIIYnBBq' +
  'CeYC3/yq9VvvT+ir3e7VNd5Z0y3eu+I35a/x3vc2A4YKARaMFkUfiCIrITMmtSAgHQAYCxB+CcoCiPsS9b7uMufe3uPZkd/N18Pg' +
  'SeTT53jxw/f8AMYH9hDMEiwbwx2FHVkinB3yGbUViA4JB5YBl/ql9P3xq+tX6THke+aZ6GLnsu3+7oLzrPfp+/0AmwWFCZUMLBFl' +
  'EfcSfBM7EGwNBAraBSQCUP91/bP7Y/s2+0r7ffzU+178Gv0R/Bv8jPsB+w777/pu+1v8Pv3D/lIArgH0AnwE9wXSBrQHPAiACKsI' +
  'hAgzCLgH1wbIBaUEMwNQAcj/zv37+6v6KPmG+EX4VvjM+ML5t/rT+639HP/1ANQCngQsBoMHXwgaCVwJ8giVCIMHJAacBNEC8QAq' +
  '/3H98Puy+t35RvkN+T35c/k6+j/7UvzM/TL/uQAfAngDlASDBS0GUwZkBu0FSwVoBGUDUwIrARgA3v7//TH9i/xI/Pz7CvxY/L78' +
  'W/0Z/uD+lf9TAAcBfwEPAmMClAKaAosCUwIDArwBPwHMADgAtf8w/63+ZP4m/hf+H/5S/qD+7P5V/6v/+f80AGYAgQCFAIQAZgBL' +
  'ACIACwD6/9r/xv+d/2z/Pv8E/+P+zP69/sv+3/4Y/0T/hP+z/9f/9//x//7/9P/e/83/sP+T/4r/hv+F/5T/jf+M/4P/bv9l/1r/' +
  'U/9W/2D/fv+R/6j/x//V/+D/6//i/+P/2P/I/7z/rv+t/7j/3f/j/w4AGgAmAD0ANAAvACkAGgAIAA0AAwD5//z/7v/n/+P/2f/V' +
  '/9r/1v/d/+r/9v8NADMAVAB+AKcAwQDdAOYA6ADbAMUAqgCBAGwATQAzACcADwARAAkACgARABoAIAAoADUANwBGAFgAbACIAKMA' +
  'sACqAKsAmACBAGYANAANAPD/zf+7/7P/sf+5/8j/2//n/wEADwAXABgAFwAUABIAFAAQABAADAAGAPX/1f/A/5v/df9a/z3/LP8l' +
  '/yj/Of9N/2f/h/+i/7n/zv/Z/97/3v/d/+D/3v/d/9v/0f/H/7P/mf+B/1//R/8q/xf/EP8N/x3/Lv9Q/2X/gv+Z/67/wP/I/83/' +
  '0P/T/9D/1//Y/9n/2f/O/8X/v/+u/6D/kP+A/3z/e/97/4X/lf+g/7D/wf/D/8L/xP/G/8H/wP/E/8T/xP/O/9P/0f/a/9T/1f/R' +
  '/8L/xv+9/7v/sP+r/6r/pv+n/6X/p/+n/6L/ov+g/53/pP+s/7f/wP/I/8//0//a/9z/3P/W/9P/zf/F/8H/vP+y/7H/s/+q/7H/' +
  'vv/C/8T/zv/e/+v/9P8CAAEABgAMAAoAEwAXABcAGgAeACIALAA1ADYARABLAE8AWQBcAGUAdQB7AIgAkQCdAK4AwwDSAOwA/gAf' +
  'AUQBYwEzA3ABbgElA8sCPQHlBMoCFwE5BDYDsgEgA/oC4AHpArIDTAIyBKoEpwaLBwcB4QdkCIUEJAdIB/gE3gRxB6YELAfAB6QE' +
  'xwdtCdwGLQffCWgHKwipCg4IFAd/CSkIpwbSB/UG4QXPB+sFEAXaCHwF3QMoCCYGOQVeBdAG/QMDBYMFHwb6/8ADogeP/PkEgwTA' +
  '/WoFmf4U/5EIRvu6AeME6Pw/ASX+JwII/D4BFQKI+aMDmP7Z+tgDavss+TUJXPZ2/L4FiPPlA7f6v/3f+0X6jf3o+mj8fvsr/zv1' +
  'SASi9nH9j/tH/P/9svi+AKz05wTZ85z7qQO48tv+GQGM78IFA/ac+cr/0/VL/EL/D/gd/Qz9YvfAAdn24f0u/Mv5APwv/dz2PwKR' +
  '9z78if6y+Of9Zvw59/z/dPiI/b//qvZEAWn98vjaATz5rQB8+yH+rPzm/TT6GQA1+Zb/zPuM+3QA6PouAQP8Uf7L/Qn+D/2R/Vr+' +
  'af4F/KD/Ov3H/QUCCvhIB9z2YASi+/T+mQGX+hMDa/tCA9381AAn/2j/8f2r/mQA4Pz5AEn9mf6HAQn9RwLf/FEDtP7s/ywAUwAU' +
  '/kwBYgC5/dACd/yIAlD/tP89AUEAxwBbADAACgLw/UgADgFk/zMBPQBI/8cA1ADW/7n/CAJe/woAJQAaASz/8wFH/d8Cu/5XALwB' +
  'cf8/Ad7+awK5/9n/9f/l/qoBU/6kAqH91gAbAIr+VAKK/ZT/NP82AEr+zAFX/jgB5v5BAdT///5NAXP/3v/YAFL9MACjAIb8FAOr' +
  '/L8AugAG/KoEzfvcAHgASv6yATf/0P0lAb397gAiALr92gG6/dz/BP/K/4f+9QCK/LgCd/6R/6T/EgDr/28A+v7E/g4A7v5Z/ykA' +
  'EQFM/l4BnP6//2L/UADU/0YALgBA/+gAT/6NAbP/2P/BADv9SQLK/cYAlQBw/1MB7gAa//ECEf8oAej/OgGV/9UCa/ycA6n98AGw' +
  '/uwBfP8aAhD/AQKK/+kAewFaAJAA5gBE/64D7P3YArP+WQJu/58BpAC7/6ICDgAtAYMAsAADAFUA0ADmALsASgDa//EAov7/Ak3+' +
  'ZgK0/w8CpQBDAJsBhwAqASMB1P/M/4gBbf+fAY8AngAZAiL/9AAMAs/+CwQQ/hkEmvz+Bbn71wM2AD3/XQFeAEcAQwGhAMP/eQKd' +
  '/wACJgCHAc4BjP9FAT8ADwBsAXYARAFTALQBhf++AQgAcgC4ANYAav9qARv+vwLN/foCsP/mAHMA8P80AKMBOQD4AH//IABV/4EB' +
  'if6+ATj+lAB7AG4Apf8TAmH+sAFh/74A///P/4cADgBMAKD/fAFo/p4Bwv27AIz/ef/PAHH/kv/A/9X+VgE8/lIBr/7BANX/VgCi' +
  '/lwB4/1pAML+VgCKAP/+ewDM/rb/cwAX/wf/GwEY/e0Bnf33AMz/TP8KALb+IgCIAHb/cwFq/0T/sgCz/ssBWv6GAMX+r/7h/vn/' +
  'Xv33AMT9qgFv/6v/HQLX/YcCuv/R/4QBff7UAIkAgv5xAYL8rgCl/fH+uv5Q///9bv8m/SX/bP/B/vQAYP/EANkAYgFJAagChwF4' +
  'A+cAPgPOANMAeQDn/7L+wf02/Yz9F/uW/FP7PvxT/Br9h/2O/1YAaAGLAv0E/ANrB1YFlQh0BccG4gMiAw8C8f6l/s76PPoZ97D3' +
  '0/UQ9r70svdO9+v7BP1SAesECAexC6oNKA/4EMsOqQ8/C6QJQgU5ABf+J/f49OTvK+2E7JzqjOxp7unwbfav+VwA2QXPCcQQVhK1' +
  'F1wYzxfgFxET0hH3CmoHWQBQ/IH0y/BL617oveZv5enmg+jI7ODwVfcS/ooE8gxWEbUYXhv2HUIgbxvzG30TvxAiCMACHftD9Jjs' +
  's+gs4urhfN/04H7kjeZ37lHyLfypASQLpRJbF0IgLh9sJVUh8h+8G5ITOg+tBF/+kfUO7bjlD+Ek26fcVNpy3rLi2uZ/7272Ff+w' +
  'CucOpxxiHbgm2SZ5JiYnqB4NHFUR8QloATf2Ju9o47ndetlj1A/ZQtbc3qbjr+lm94X79wr2EXgbkCN6JysrtivfKNIk5h4yFBYP' +
  'xwDn+orul+Sm3T7WPtPw0ijTYdl739Tm+fKq+4kINxMLHfEktSvuLEwveStaJgEhZRVRD5gCJ/qw71PkcNv51U/QmNHS0pDVuOAj' +
  '46ryi/qIBkMT2RuvJMIrHy7sLmAvxSUqJZ8VGhF0BLT5j/Ea5O3aQtTUz0fOhtSx0kbinuSZ8WL+4AWCFbsd4SN4LXUthy2HL70i' +
  '3yNEFcsN0wbM+ELzAeYb2jbUWNAkypTWSNAC4kXn8++KApYGtxaZIIgjUC5nLXcrBi4aIIwhohMwDbUGkvlz9c3lvNzy0ELRN8il' +
  '1KDR797c6TXv8AM6CJIXnR+RJ2kpyDEOJwwuXSDvHCEW3AeSCL/3i/WS5p7b5tDnzw7Kk9Ih1q/dPu468m4Ffg0hGWIhcigIJ2kw' +
  '/CRWKdweyBcLFcoGZggC+ln34ej13dTPkM82yh7PUtk624vxevQMBykR7xjuItomJSm2KGkpTh75IZkSMRNrCKEFcf4l97Hsmd+D' +
  '0cXNr81ay0Xc9tnR8TT4aQaUFOUaXyNbKK8oSieQKC4cQx5BEvIORgkEBEj+8fnI7RXhbtLRy0/OXMnH3Dnb7vID+8kJUhZiHiQi' +
  'tynlJKMlCCOGGVoZ6A8SD4gGfwi1/uL8+vHd4TfVcMljzw7Iwtuu3HvyDP4hC0cXrh/7ImgmhCblHicidBV+FrEOEw6TBiwKHAC0' +
  '/rv1juOK1ujGANCMxOnbJt2d8bUD4AocHSogVCUgJF4lsBsQHY8UPRCoDrAMPgeDC3MDIgDm+EnmnNU6yKDNWcXq2Wbfk/FeBVQO' +
  'Wh2VI0MkYyMwI5MX7hjXD7EKzgyFC08Jxg7SBiYFhP736e3YhcaPyzjD8tPA3vjs0AVfDVQgHCRdJ0AikSHLFSYTjhC+BmENgAkY' +
  'DN4McQ07A9//Suv91RXFKMpOwmHUueJi8L0KuRPkIc0mDSdCHt0f2RDBDp0NpgUYDK4Nlw2/ELQPFwXiAdjqbNRCw8rI+b581FPh' +
  'HPLHC/cWiiMVKXglwB0aHHoMtQuCBy0FXAc5EVQNMBRnE6UIPgQc7e3WEL8oxze9ytBE5CT0JQ/tGococChKKKoYHBalCBMDCwUx' +
  'Ar8IqBKfFKoZcBitD70Cuu9d1MC6A8RruvfMPOMr9EgPuB1TKbwq6Ci5GbgTowcAAO0AYQFGB04V2hZbHBkdIBKeBfXwLNTvuOjC' +
  'XLVszaviDfZzEtcgOixBLGcoIhbgEGYB6Pty/fL/7AdwGJgYpx5gIJsTkAk+8vfTSrmPv6S0lMsM43j21hSRIWosJyyNJe8S9ww2' +
  '/kT4i/1A/o0KURqZHYIgfCX+EZoIUvHu0Ry207p3tCHILOaT+FoYyiZzL3otKyefDjkI3vdl88/3lv7XCysdQSRmJskpfBh6C8by' +
  'ptQRsP+3+rAIwlflyvb0Fx4oJC9tK4onFwynBcX3e/GR92D/vAvEICknDCbtLNIXswv+8ZLWOK96t+qwEMLp57/4sBrCKAAxQClW' +
  'JiIJgQC+9DPuffZxAOUNhyJJKzkoyC2HGesLgfKD1g2w3bTBsSTAB+gM+gIaWirUL9spfyQKCDr+cfKE7YHzOwK+DLklXC2NKU0w' +
  'oBhnC9/zStkWsb6zlLWIvRnp5vkqGNMpZi+BJbck5gYA+ijzo+2H9GgC9RAzJKgx1ylcL4wbWgvk813bOrIQshO3m7v56UP5phc0' +
  'KRMvGyT3IsoGqPfb8uDrnPX+AsIRpCTgMXIqNi+mGxsLGvVv3Em2l7IDun68Iunh+48UhSinKxQiDh9hB+3zAPTG6q31ugMuE/Uk' +
  'PTOdKp4sWR3uBp32fNtSufOwRb6gvdnqbv6tFW0oSCxKH/4bPAXB7zDxDuvH9dMFZxYWJzI0Jy04K7UbTAZB8x3aMLd9sSbAtb8L' +
  '7gkBfRbiJ5crORxFGQYCbu217jHtkPZqCZga5ifMNYMsXSgwGQgFv+4U2qC2o7P+wazECfBSBPIYQiZ2K4UYchXN/QzsBO2q7Y35' +
  'bAtlHhcr6DUuLIgobRWdAizrhtX3s9S0s8SqyVL1wwiCG0wniSiLFnIPIvuL6PnszPDC/J0QziHhLPE0mCsgJNkSBf8n5iLS1rCZ' +
  'uq3FEdGL+9sLKR6iJ4EmRxIdDTP0r+ip7HTzAAHTFY8koy9GM1wpHSDtC5z5x+CBzJawcsFbyJfcsAFLElIgcyfFIcUNXQZO7lnn' +
  'oO2994oGahzVKOEwBjGpJb4aiwa78qna98VbsEDHHMxY558IkRceIjEntBt8CUkAO+rs6GPwEf79C18ifSvuMZAtvyObE6YBreqp' +
  '1Vi9R7N0zGjPnfTdDdwcRyPoJuESmwY++A/nxOkE9t8CJxOYKJssqDICKiMgXQt3/NfgZs7WtBq8Jc0E268B9RM6IiwkfCLWCqsB' +
  '2O7o5v/rA/yOCGkcPCxXL3QvSCbJGAsE9fQT2AzHHbNRxaDSp+jDCsMa2CInIyEa5AO2+ZvpjuYF8ZcCog9ZJGMv3jCcLNMiDBBN' +
  '/drpGdDOvv202M/Z2Cj5HRR4IJchviDtDo77+/GL5d/p1/hdC+UXwyw6Mdwvdih7G7wF//WH3BjJrLWUvyDVFeQ0CrsbzSRjICMc' +
  'uALE9hXphOUL7pMCohGAIqIxkzFBLXMifRHx/PzqjdARwSuyCs7g2QT26xVbIpkiPR/YEKj4JPCx43zoefbKDCoZ2S0JNE8xAiiR' +
  'G2AFOfWL3TLKt7d4vTXYguOcCP4bPyQgHWsatwG48pzoXuXB7VoDWhRsIy8zDzNWLN4gXhCG+6HrONK4wxi2ps903Bv2OBOjIHMe' +
  'yBqZDoz3Y+705crqKvjpDscaBy0PM04wgiXZGbkEw/Q03yLLhrvGvjjbIuVeBwIbyyF1GWMX2ACx8L3oTOfN710E2BbOIoczxTFQ' +
  'K4ke5A/i+THsTNMWxmu4stGc4ED1zhOEHqMcchZ9DdP0ae1a5p7sHvkOEa8bGy3xMt4uliRhF8EDefPU32jMyb5Uw1zfc+cNCcUZ' +
  '2h2ZFeESYvwH77PoEulI9PwHSBoXJt0zUzD5KcsaBww6+HvpPNMpxxS8i9cq5IT5FhWJHFsXpxJzB9rwduyt5vXvrP3aFDofBC8P' +
  'MscsWiFgE1gBbfLZ3obOVsHCx4Ti7OoUCu0XdBs/Ee0PDvoO7xzpqOtp9sAJdBvQJZEyri6yKHcZ9wpr+GLpwNN8yBW+2dlO5NP6' +
  '+hNMGo8V6hEjBfbxVe086O7x2P97FXUepS4vL3Ir+R/0EjAABPPq3T3P0ME7zCPjK+yHCpkWuRcyEK0N4PY6743poO2d+FwOJhtc' +
  'J4kwsCz4JGMYXAn0+EfqztT3ytHCmtyK5bH7ExB9F8gQDg9zAjTxH+4Y7Nz0SQTAFxgfziz8LPgo2h1LEnv/b/ON3ULQY8ML0TDj' +
  'he6UCq0UkhS3Dr8KZPUT8EnrI/Df/GgR3hvMJ/IuAyp0I64XNQfy97LnmdIPyaPGYN9L5ygAIRJXFe8P9g14/l3xD+/z7X34WQmA' +
  'GQkgrixKKkYl5RvmD6b92/G53P7P68XT1OPllfERC20T/BCFCyIHwfPO8FLu1vTpAMsV+xsGJ04rLyftH1gX2gWp+HjmudSEyU/J' +
  '7uAG6OABbxCVFFUNdAz9+xvySe9A8X36KAzOFwAgOyqRJ0kkzhpfD8n92vEV3PzRd8Wn153m2PL6CvoSRQ/eCisGE/Wh8VbxovVV' +
  'AQoT8xhfJH8pZCb/IKAXxAcd+W3mltbLyj3LoeNY6RQBVg8wEtsKSQqc/PLxuvHC8h77JAvpFrcdbigAJwMkYxtREA//1/B23WLR' +
  'u8iZ2ovlpvOsCWMQSQ3FCnEFK/ZA9JPyUfj0AhkS8hiDI8wm7CR1HtEVXAaP+aPlmtfHynnPK+Md6R8C/g1MD3AKdwoH/NP0UvMX' +
  '9X79PAsgFu0ddycQJv0isxmWDon9uu7m2nTRPsix3P3m+/WBCyEQngwVCu0D2PXD9J7zBfqsA9MSqxfZI0UmqSRqHaoUVwR09qjj' +
  'PNXYymvT4+Mf6wUGPQxXDiUKMwnm+h/3l/Sm91v/cgz0FFweRCVMJd8gMhjEDPb7/+xb2pvQ7stg37Dl/vgICvwMLwviCbUCjPhU' +
  '93n2rPxwBdsRdBhNI+okrSRoG/sTUwMi9K/gE9X2yfXTseTe7DYFogw5DoEKpQhf/JP4i/Yc+goBOg3UFPseJiVMJfUfIxebCaf6' +
  'medt1zfO7s2V3w3mov40CcgNPAy9C+EArfsv98L4z/1pB2MRdxq/JAslHiSfGoIQov8d753byNFCymPaHOMp9IgGnAvGDPwLIgYT' +
  '/Wz6tPdd/ZoDnA6LFn0hdSSAJEEdoRPqBaj1s+IW1ifMb9Iy4X/p1wDZB98L/AsXCWcBlfzH+dz78gKoCRQUxhyFI78ksiC3F2cM' +
  'K/yB6vzYwc8jzBzdv+Jg+IYEOQpiDN8L3gVDANf8sfucAeIGIxBcGK4hgSJsIlEZZRALARjxCN2702jLRtc94LDuQQJYBZMM7wti' +
  'CR0DVwCh/BQCjQUxDcQVkB7pINkiXRu4E1AH+/Wv5U/Wts5Z0EjfFuXE+pwCHQkuDeILzQfbBLEA7wFJBv4J1RFkGQgeHyBYHIEV' +
  'JAuE/Cvs0NqK0l7NMNtq4J7zEf9JB8UMVw7WC9oIkwTjA8AGEQlfDxIVMBvcHJYb8BQSDZr/SfE44ADV1c141lTelOxJ+4EG/Asg' +
  'EUcQZA11CXUGIwaRCREMdhEPGLwYMht2FDQO7QEw9HXkX9eT0l/O5t0V5Gb3CwO6C68T/hPCEnAPUgpUCKkJgQnHD3ESAxZIFugT' +
  'RQoWAeD0Rejl2z7WPNZb2MDlb/B5/ooJORGHFSIYuRKDEJ8MjQkvDFEMwhDgEjAU5w8FCHz9U/G163nca91l2YHcuuUA76/52wYk' +
  'DKoUbhhSFVEVqw/iDnwNdQ2iDhkRnA+FDV4Clvmh6wPqGt5O3xng+eDl6pvxt/oaBFAKTw+mFgQUGxbYEj0RMRFeEBoPPRGtDQQL' +
  '9/589MLopOT43kDeI+Q/5Hvv2PXV/aYFvQhKDR8SCBI+FDoTDhNEE3MTXhFQE3QNZwpZ/sLwkubd3r3eZ9sH5QrnKPH4+W4BVgd3' +
  'C3ULBhCREKoRdROMEnoTOBUgEvASLQ47CC3/Me+/5fjb7N2e2lDkkelp8WL9JAKJCp4LYg3xDfUQmQ8pE58STxK6Ff4RWBLzDs4G' +
  'tQCr70bmONsr3D7bGuEJ6wPwpf3BAxQLvw6jD9cO8hLmD9ISHROqEE4URhEYD6ENGAV2AFjyheay3enZBd1i3hvr0u6F+5kDFwpu' +
  'DxER9A/kE7IRcxP7E1ER8hJQEWsNOgyIBB//FvWS5ingctiO3fbcXeld7nb4IQM3CB4QqxEWEjoUIhSdE1kVdxFEErEQmgxkCoIF' +
  'zvxu+L/nDuKO2cnbhd6u5MLv9/NUAp8GIA+EEkETkhRKFmEUzRVuE/oQBRFLDIQImwXi+075M+pq4ubbXNqf3vjiPO4q8gsAJAXU' +
  'DU4TYRNHFiIXMRW5FxMTRxKLENYL8AgDBGH9mfgI7sfi594E2b/fpeDb7CPxk/zuBOsKJRNoEw4WGxg+FrAXWhW0EQcS3gs1CWYE' +
  '5P2F+FDwROPz32rZpN5V4Ozq5O8l+igEGQhLFIQRWBe+F+8WCxgQFigSIRLRDG0ILgYu/bz6nPG95e3hRdpo36Df1Ogp73b2wwKY' +
  'Be8RvhFGFj4YAxggGJkXrRLHEnAN0QiABhH+Qvv+8nrnE+PO28PehuDa5ZjvCvPsAdoDvA8NEokUchiqFwsY5hcTE+USSQ5gCTYH' +
  'cP+X/Hn0TOvo46belt564fLjDe828HL/3wEzDO4RqxJuGGoX0RhjFyEWaRBCEsoHcQjAAdD6U/m46yHnyeBj3uniXuJ77XjvfPvi' +
  'ATQI4RHxECYYyhaJGAQYHBWpEjYQxgqnB6ACgv0V+Qzx1+gs5Krfg+OC4sXqD/Cg9bgC4AJAEZcPXhZUF3kXMRh+FYYS6w8gDO8G' +
  'nAQ3/tv6/PR77Mjn9OJW45vl1ubr8PLwOv/eAO0KshDaEJEYdhQFGbQUvRNFELgM+AgABCUBQfss+Lvwq+oU57zjyucG5jHvsvCV' +
  '+fkAxARfD14OgxV9FGoWJxVhEzAQUw2zCcEE+AKA/LP62fSE7hLsj+Vq6UHo5+pm8xnyQwDV/60JFg5nD7wUdBOCFL8TMRBEDhAL' +
  '9AXFBEX+VP2a9zL0Z+4F7LXnh+y66DzxZ/IN914BwP9uDWAK2BH2EagSQhMHEaoOFwypCNYEtQLB/Vb8hfc89HLvXu2A6hXuMuuF' +
  '86byNfqW/7cBpgtZCbsQpw8KEY0Rww6pDbAKzAfTBBwCkf4y/Lf4D/Us8uTuv+0m74vtJPRH86b6//3YAVgIKQmyDYEOkw91D40O' +
  '3wupCt8G2QQGAtL+Pf2D+ZL37fPx8dHvHPGT72X0Z/Qe+bj96P4MB9wF+QsdDKQNkQ4SDUoMIwoOCCIFogOm/+X+Ffty+cL2dvSW' +
  '8ofyYPIg8/f2JfaH/dn8+QJBBf0GGwt0CtsMEwxYCzcKbQgFBnoEUwGw/1n9Kvvq+XT3Cfcv9Y71D/bg9Zf5rfjH/Sj+YwH+A8UE' +
  'rQe9B+0I0whiCHcHqQbFBMoDsAFJAOv+P/2Q/B77kfoi+qP5Ovo/+lT7Nfx3/dr+y/9LAcsBFQMgA84DeANEA8UC3wGJAVgALwBj' +
  '/2X/Bv8Z/xH/cv+g/0MAegCjAJYBUQDIAfP/gQAt/0D+Rf2R++j7nPr0+yT8Nf2Q/7b/KAMtA1UFEgbjBQcHFwVfBWwDJgIXATT/' +
  'd/6Q/YX89fwf/PP8hv0U/gAARQBSAr0CsANcBA4EeARtAykD7QEfAQEAIf9D/rH9Zv0p/XX9d/0X/kr+4v5G/8j/OwChAPcALAFo' +
  'AU8BbwEcAQwBpQBjAAoAtf+B/yv/Gf/e/uL+4f7h/hD/Df9C/03/eP+p/8f/FQAvAIUAmgDJANMAxQC4AIcAWQATAOP/n/9+/1D/' +
  'Ov84/zb/U/9r/43/s//S//7/HABDAGUAfACfAKMAsQCjAJEAbwBBABcA6P/B/6f/jP+F/4j/k/+w/8b/4/8IAB8APgBRAFoAbgBl' +
  'AHIAYABSAEoAKAAjAAEA7v/j/8v/1f/K/9b/5//1/wsAHgAiADIAOwA1AEMAKwAwACEADQAMAOn/6P/P/8L/yP+z/83/0f/l/wUA' +
  'DwA4AEMASwBdAEkATAA6ACQAIAAAAAAA4v/Z/83/tP+9/6L/qf+e/53/pv+s/8D/z//o//r/CAAWABoAHAATAAUA///p/+L/zv/D' +
  '/7H/nv+c/4j/hP98/3X/ff+E/5X/pf+4/9n/6v8FABIAGwAlABIADgDw/93/0f+2/7P/p/+Z/6b/mf+5/7j/zP/i/+T/CgALACAA' +
  'JQA2ADoAOAA9ACYAHwAJAPP/6P/U/83/wf/D/8X/zP/S/9v/4P/r//j/AgAIABoAIgAoADcAOgBDAEAAOwA2ACQAFQAEAPP/4v/P' +
  '/8z/xv/J/9P/2P/s//f/CAAVACQANgA/AEoATABIAE8AQwA+ACwAGAANAPb/6//Z/8//zv/K/9P/1f/h//D/+P8IAA4AGQAeACMA' +
  'JQAiACMAHAAaAA4ACgABAPf/9f/l/+L/3P/e/+P/5v/x//X/BgANABYAHwAfACUAIwAlACUAHAAXABQAEAANAAYA/v/9//H/9f/t' +
  '/+//9f/1/wIABgASABsAHgAjACgAJQAiABsAHAAVABAACQAEAAUA//8CAAQABgAJAAoADwAUABcAJgArADUAOQA7AEAAOgA3ADAA' +
  'JgAaAAwABwD7//b//f/1/wIABwASACIAKQA5AD0AQwBPAE4AUwBOAEoARgA6ADYAKAAmABsAEQARAAoAFQAOAB8AIAArAEQAQgBh' +
  'AFkAbABxAHEAdwBpAHQAcABoAF4ATQBNAD4AOQA2AC0AJgAfAB4AIAAjACoANQA/AFEAVwBgAGkAaABqAGEAWgBOADsAMQAhABwA' +
  'EwAPAA8ADAAUABAAGAAbABsAIgArACwAOQA6ADgANAAxAC8AIwAbABEACAD///b/8f/0//P/9f/4//j///8AAAgABAAIAAsABwAP' +
  'AAoACwAKAAYABgD6//f/7P/j/+T/2f/c/9b/1//b/9r/5f/k/+z/7f/y//r/8//9//f/+P/9//j//P/4//T/8P/o/+f/2//a/9X/' +
  '1f/W/9X/3//e/+L/4//k/+n/5v/u/+j/6f/k/+H/4v/Z/93/2P/X/9f/0//O/8//z//P/9H/0v/b/+H/5//r//P/+P/5//n//P/4' +
  '//n/9f/2//f/9f/1//D/8v/x//T/+P/5//3/AgAEABAAEAAYABkAGwAgAB8AHAAaABYAGQAXABYAGAAQABUAEAAOAA4ABwANAAwA' +
  'DQAQAA0AFAARABkAGQAhACYAJgAqACIAKQAmACYAJwAeACAAGAAQABEACQAOAAcACgAJAAQACwALAA4ADQAPABQADAAPAAoABwAF' +
  'AP7//v/2//j/7//n/+T/1P/Z/87/0f/M/8f/yv/C/8v/x//P/9H/0P/U/9D/1v/R/83/zv/K/87/yP/G/8L/t/+3/7L/r/+v/6z/' +
  'rv+t/7P/tf+1/7z/vf/B/8X/xf/P/8n/zv/M/8T/zP/C/8P/yP+5/8j/vf/M/9n/0f/q/9z/7v/t/+7/8v/x//n/9P/7//T/8v/y' +
  '/+z/7//u//H/7v/w//L/9v/7//7/BgADABAAEAATABwAGgAiACIAKAAtADAANQA1ADwANgA4ADcANQA2ADAANAAwACwALQApACwA' +
  'MQAxADgAOwA/AEcASABOAFYAWgBgAGoAagBuAGoAiwBqAIMAegBjAHQATgBaAEAANwAuAB4AHwAPABQACQALAAsADQAUABEAIAAh' +
  'ACEAMQAvADUAQQA6AEUAQwBCAEUARABCAEAAOAA2ACoAJAANAAwA9//u/+T/1P/R/8j/wf/E/8P/0f/M/9n/8f/s/y0AIgA9AHAA' +
  'XgCJAI8AiwCYAIsAfwBuAEoALwAOANr/yf+W/3v/Zv9I/0L/Pv86/2H/TP98/5v/of/v/97/LAAqAE4AgABVANwAbQC/ALwAZgDD' +
  'AD4AVQAaANr/y/9h/0P/2f6a/l7+7P3Q/Wb9PP35/PD80/z5/Cv9cv0R/of+bf9WAEwBmgKuA7ME/wWsBoAH7QfrB9AHJgcdBssE' +
  'PAMHAXT//Pu3++H4IPch+I/0/vZw9ib3D/rS+jf+JQAgA40FMwdECo8KbAz3DJAMLw3iCyIL8AnTB54GrwM+AtT+Z/zy+Tb3DPPo' +
  '87XyfO0O9WjtPfJu9Zrxffon+Bn9ef+E/xsFjwHiBq4F3ASuCOgDsgfYBZ8FAAgLBbYIlgYVCPcI+gZmCV4GngbbBD8CvwE5/WD9' +
  'IPjf9jv0JPGJ9OTsA/Rn8Pnw4Pji8v38Pfyb/hkFFgKMCQsHCAocDLUIWw7BCEMMbAtWCOsMmAYICiIH7gQ2BoEAMQJq/UT7G/oB' +
  '9Cv1Ne+d74HwDern8Y3sV/Dy9WryofwA/HsAkAVjBLwK8wijC7oMRQrfDdIJXAv3CioINgtJBwoJagiTBk4I9QSgBYsDLAHOAP77' +
  'gPsE9/HzFPJR7Q/wJOow7T/tmuu38zrxN/hX/Nj9VgWHBeIJ5gsLDMoO3gxXDoQMMgyUC24JgQrFB8oIowcKB1sHrgW6BaUDiQKF' +
  'AHL9a/se93r0dPD67ejt2ugx7K3pOeuw8KPvkfdi+mP+uwTTBQYLAwzUDTcP/Q1KD7YMCg1uC6kJgQpzB5IIpwdkBuUHmgUxBksF' +
  'PQMEA8H/p/0X+2z2sfQ179Puh+zD6KLsl+dH7RTvOPDU+Cn5dgAqBGQGGQxaC0gPjQ6bDkQPIQybDSsKHApoCe0GjAgrBgkHqga6' +
  'BaIGfwT7BJgCPwER/477//j99Afxze5p7e7oAewK6Mzq1O627Z32q/d0/SgDTAQYCxYLfA6YD2oOWxD5DPgNnAvnCSkKyAYlCEoG' +
  'QAa0BnoF4gZbBd0FvAQcA6QCk/5U/dH4dPW28T3uwe1R6GHrdOe76e3tm+yp9br2s/ylAtMDKwscCxUPMBA0D2MRcQ3eDvcLPwof' +
  'CnQGJggbBUsGzwWoBGgHJwTlBvYExwOrBNn/2f9Z+3H3PvVZ7tzv0elr6VnqmOUm7QvrOPCL9nH35QAbAtoHJgzQDLcR9g/UEW0Q' +
  'ew7BDooKsgqxBz4GCAZDBCkFMwRvBRsFtQVBBjUF5QXCA4gCov9q/GH4PPSk7yrureme6GHo0OUg673q4e+t9SD4pwDpApsIugwN' +
  'DmsS1xCkErsQ0g6pDjoKXgpeBrkFzQSdAo4F+wHzBR4FbwTWCBAELghABSIDSQOA/KX77PXk8ObuHOt65/roIeUk6EPrtet49AD2' +
  'S/3jAjsF0wzuDHcRSxJsEaQS4A4DD6cLrAkgCJgENwWHAlADTwSdAuoGfARgBxUIDAZLCaEEUAWnAQ39tvrY80fw5Ozj6MnmreY1' +
  '5HjoqumO7aD0Qfe1/4YDIAjKDZ8OrhJoEjwSshGwDtoNVArDCCsG0QPKAysBnwM5AggERgakBLoJxAaFCR0JEQbxB90AhwAP+nH1' +
  'vvGo6oPrwOMW59DjVeX/6lvqtPSC9rz9tAQ0Bn4OVw5TEmUTphHgEooOQQ7wCkMIKQdwA2EDQALoAE8E0AElBm0GMwbWCuEG8woY' +
  'CFQGfwaj/u3+M/ai85Dt1umO6DvjnefL4s7pT+tK7234UPnTA+cFywoCED0P5RN7EagRKhCQDLELuQdeBt4DHgLFASwAfAJ/AUsE' +
  '7wUABgIKbAjGCpAKOQgwCY8DnwGz/DT2yvMN6wTsLuVx5RLm+OLB63zp6/JL9xj7HgXwBCcNPg4SEBoTHhCQEdUNFgz/CYgG1gWE' +
  'AtMBmwGZ/yYDLAHXBKcG8wWYCyYICQzrCnIIVQp2A9oCU/2H9uj0HetE6zLnKuMf6PnhxeoQ6xLw/fjD+XQEMgbrCoEPrw57EmoQ' +
  '5Q+MDu4KjQlwBqQE6wK4AXUA8wDPAAwC1QMBBa4HgwhiCgMLHAv2ChYJlwfBAx8AUvtR9cjxmOr26UPmE+QT6JHj5exe7DHzlfoA' +
  '/FQGtgYjDP0ORg6fEbcOqw6vDF0JLwgdBcoDdgIXASgBHQBiAigB7QQfBe0GEwpaCJUMwQnwCqYJWwa3BXb//PxK9lvy2ewq6cTo' +
  'b+Pk6A7kbOtH7RbxVPrO+rMEOQZmCj8OZQ1/EHAOAA6ODIgJHwieBQQE0gLcAe4AawEQAcACMgMdBZgGrgfbCXMJTgvfCcsJSgg+' +
  'BYYD3P0g+3j0e/E56xfqeudX5VLpPOWA7ijtGPVF+vv8qQXUBYsLtAxHDVIP/gxJDR4L1wipBwwFLATqAswB0QEMAY4C1AGABIIE' +
  'TwapCIIHlgu5CCYLTgmKBw8HEgIqAO367PWy8vXrousG6F7mxemg5Y7umezV9AH5Pvw0BIYEYwpWC1YMYA5NDBwNxgoxCewHbwXK' +
  'BEgDYgIcAowBJgKDAsEDZAStBsMGUAlVCQ4K5gq2CNQJvAXuBIUAavzF+GzyO/DM6XLr9OQS6jjm2+ow7rzv+vgh+bYB1QMyB2QL' +
  'mgreDZoMgQwbDG0JAAmCBjIFiAS6AgcDswGSAlcClAN4BIEFfgeeB0MKbgn5CioKEQmWCPAEcwP//RD7lPTk8Qvrmesr5rnna+fh' +
  '5pLtjeyy9ZD3i/3cAowECwoZCn8MJg0CDN8MNwqpCfkHzwXTBVYD/wNYAr8CMQPaAkYFmQSnB50HgQlZCkgKKAufCUsJ5gaCBMAA' +
  '3/zI91fz4+5D6lHqlORp6cLkquor7J3vFPdt+HcAcgKHBhYK2QldDa4LrAzSC78J6gnIBusGFgUhBFAEqwL4A5UDSgQsBvIFmAjl' +
  'CO0JcQsyCnwLYAlhCFYGdQJU/9v63/SY8qjqb+sP5gjmoues5PLsserD82j2Q/sNAu4CMAl/CXoLVA1VC04NaAoWCtkIWAbbBhIE' +
  'zwRuA3AD7QMOBPwEpAabBnIJ3Aj/CrsKvAq3CuEItQcjBVEBP/74+Eb0zfD96S7rjOTB5+/lA+eT7D/sIvXi9h79XQIMBPkJfglh' +
  'DMEMmAvcDOcJ6wkxCBYGiAabA+AE9AKjAxoE/gMdBlkGBQigCaYJ7gu/CsMLggoBCawH8wPUALv85fZ880DtM+pg6PXjSujL4+jq' +
  '1+px8D323vjdAJQCgwdQClwKoQ0/C48M7gohCQcJ+AUzBnMEnwM4BG8ClwSxA5oF6gacByMKcwq/C7oMfQumDLcJPAnxBVoCvv5g' +
  '+Uf0KPC+6dDpBeSX5j7lH+fx693sRPWF9yX+DAM5BaoKCgraDEsMXQu9C8IIuwheBigFxgT1Ap8DAgMzA/cE4ASJB88I6QnoDOoL' +
  'hQ7gDLQMrAsoCPIGsAEU/nz5cvI98LDnC+nG4snlIuWf5m7sGO209TP4h/6yA6UFDQs9CqkM8QuiCtIK3Ae3B+wFWATUBIsCWAQB' +
  'A9oEmQUTB1wJdwqEDJAN7A2uDggNhwyPCRoHoQPS/h/75/SK8D/re+Ze5l7hFefS4wjrwOx/8az4+frLAjUFjggbDIoKKQ08CtsJ' +
  '/ggZBuUGSARlBG8EEwNqBZwEAwfdCMcJSQ0fDR0PWA+4DY0OGAqSCRgFQQGn/bP3GPOS7qjnGOd44lzjPubo5A3us+wm9if5Kf4U' +
  'BewFXgtfC44LXwysCGgJrwZNBQcGNQN7BeQD5AQAB30GEAtoC2QOqxCFD/YREw7uDXYKkAaRBEb+Mfu99ffucO1e44jnxN975Xnm' +
  'aecD8b7tJvqm+YgBlgbyBh4NHQrSC5gKRwfnCMwE9gWNBdoDPwf8A20I8weECssOrA5tE8kRLRLwECMMbAudBGwCVfyw98bx8OwG' +
  '5mLkIeHN4Bzn7eOG8LDsiPfY+R/+LAZiBfMLqwrkCmULnwc/CBoGtwS3BiwEZgdkBuUH+ApHC9UQVBHuE5gU4BGBEQUM0whnBGz9' +
  '9fqx8Xru/eZ94PXivtmK5+7gou0h8IvyBP/G+jQI8gWyCjcNbgl7DDgHswZ/BW4C8ARxA5cFXgezBxYMiA2TESsVyRR3F8wSCBJS' +
  'DJgHBAPy+lb3Bu1d6oDe9OA02XjfvOOu5Cz0D+5v/xX84gQSCrIH7g+FCZUM8gi+BaIF3wEGA7wDfgS8BwcJkwv/DzARYRYoFjsW' +
  'bBWED+IN7gXjAPP6gvHY7abjsN7S3ofW9eWd3pbvA/FR9YICQvzLC7cFkgw6DP4ILgzVBJgGCgKhAYkDhAM4CKIJ4AwFED8SSRWn' +
  'Fg8W/RQuEagMmAeU/+f5fPCs6t/iFN043r7XqOVx4FPw3/HH988Cqf7KDNYFkA1OCjMJRQqTA3wGOgC5A1kDyAbQCpcMkBEgEnwW' +
  'CRa9F+QU2RIDDoIIBQKI+WzyJOkL5MjbSd6J2FjjGuOz7M7zdfVNAlj+gArlBXoLognBBywJjALkBSwAaASTBJEIQg3HDnIUQBTQ' +
  'GMsXxhjZFfMRaw2IBS7/YPUD7Z7l19xl3LbYJd0p47blRvKb8V3+n/7CBc4IGwjRDOgGwAq4A1oFIgK/AnMGIAfqDmMOqhXMFFQZ' +
  'HhnrGP0XMBIiD2MFXP+l9PbrTOQs24Hbndct3rfiu+cR8kDzkv9V/8gHtgcWCXgKxAa1CHUCZQQ9ABME7AXXCiYQfhILGPQXDBxF' +
  'GkcaXhYWEeMK+gAN+Rft/+Vy28zZUNc821Di0uXX8Bnyd/0U/2sG8QedCO8JtQafB94CMAOVAGQDjgZtC0IRrBOpGP8YMRwvG0Ma' +
  'uBamEBwKCQDq9tXr8uJr2ubYWtdv3nTiu+pS8Cj2gv0PAVEH0AZ7CawGGwcXBAADaAHgAacFowlzEEsT/xf+GJ0btRsjG18YHRNz' +
  'DAMDsPlV7jPldNsE2TvX1Ny64UzoFO8D9CP81/89BnUGpwi+BqoGfAT/AhcCbAJaBoUKnhDDE4IXIxlDG64bBxsjGBET0wtpAmr4' +
  'N+264zXb19g/2LTdVOI66RfvLvW/+7IAlAUfB5YIXwfpBqwEuwMoA+kEjQggDXsR4BR8F3gZcRpXGr8YORWfDyAHq/3P8tzo7N9E' +
  '2wragtxA4S/mgeyi8T/4SP25AmcFcQdmBx4H5QULBbsE8AXjCLYMwhDcE3MWORhpGUYZNxjwFJoPawdU/gT0Teqo4R3duNtR3nPi' +
  'Teeo7NDxrfcL/fYB4gTXBlMHeAeyBk8GWwY9CE4LFA9lEgYV7hZbGLcYGhjKFX0Rpwo1Aqn4vu6R5TDf09y43aDhe+WZ6ijv5fQ2' +
  '+nX/1AI6BVcGBAcEB8YG+QZBCEUL2Q6KEhgVGRcvGM8YNRhUFv8RRAuWAjr5VO9f5qvfV90W3h/iHObh6kfvdfTB+aH+GQIzBHgF' +
  'LgarBsAGbwcHCT4M8A9+E+0VmhdkGHAYdBfBFLYPSwiV/yD2fOzo467ent0B4H3kwOiT7eTxQ/cR/EcAoAJdBFcFcQa+Bu4GmAfG' +
  'CVYNQhGfFLoWEBhpGOwXBhbiETULugKS+Rvwweb531Ldvt4S45fnNuyy8NP1L/vE/6kCbwS7BQkH0gf/BxYIXQk5DNIPIBNVFWgW' +
  '3xZvFhIVYxFHCwUDJ/r88HznhuCX3UXfoOM26JDsD/Fh9tn7dgBnA4wFcwc+CSQKIwr1CcEKEg3xD6QSYBQqFSsVmhTMEp4OzQdx' +
  '/wz3PO5x5ezfot6F4eHlGOo97uvyZfiA/agBSQTfBgwJ9wpWC3kLcwvCDKkO7xDjEjsUeRTIE3gSbw8BCkMC+fmz8S3p3eH23j3g' +
  'q+Qt6Ybt3PEX9x/8ggBxAz8G0ggjCxcMXAwqDHIMcg3nDqkQGBLhEnASUBHrDjAKDQMd+03zOevU43Hg1eC45MroEO1W8ab2qftP' +
  'AIUDoAZcCQQMRA2wDWcNRA3ODbEO4Q/SEFQRxBBrD9YMIAheAcz5E/JY6sHjbOGW4r/mxeoc72nzn/gV/T4BIgRMBxsK2wzWDRsO' +
  'ew06DU4NFw7UDqQP4w9MD28NNwrlBEP+4va575LoruNj4kbkHegQ7HbwLvV0+v7+HANQBq0JkgzYDogPlw/XDlgO6g1FDoMO4w5Y' +
  'Dk4N8go9B3oB+PoL9Ezt4Ob94/7jCueA6n7uhPKV93D8BwHABGIIwQvZDmoQ4BBZEHsPnQ4oDgIO2Q1xDV0MnAp4B+cCAP2s9kPw' +
  '7+nO5cTkiObd6XntTPGT9VL6uv7TAoYGUgq3DSUQCxEeEWIQtA+pDjEOeA0FDdwLOQowBx0Du/0B+AvyFOw350Ll6uWu6O7rs+/K' +
  '85r4Vf3pAf8FMwrkDesQVBKtEr4RhhDeDsgN1AwmDO0KQAlzBnUCQf2l9xfyt+w86BbmHuZT6GLrIu8b87j3b/w5AZYFrQlyDW4Q' +
  'BBJwEvMR8hCSD08OHw0JDKoKxggUBlcCov2D+Ibzpu5U6vbnuueG6Vrs4O/g82X4+PyZAeEFAgqXDWwQAhKQEv4RzRASD54NOgwQ' +
  'C5AJtgcPBYgBDP1a+Lbzce+h64XpLenI6kXtgfAL9EX4k/wPARMF6QgoDOYOexA0EfcQORDxDp0NJwykCusI/wZ0BEEBbP1f+Y71' +
  'B/Li7pXsz+t17FTuxfC18zb3Cfvl/o4CHQZLCQoMBg43D5QPKw8qDt0McAvbCS4IZgZjBPoBPf8N/BT5SPae80jxne8B77HvPPFc' +
  '8wH2RPnV/HIA1gPgBpQJmAsXDccN+g1VDUgM0AozCWwHsAXwA0QCMQDq/X77cfnP93n2APXk83/z2vN89JP1Hvc5+a37Yf7dACAD' +
  'RQUTB30IVgmpCXcJCQlNCDwH5gV/BBkDrgFAAA//3/2c/HD7Rfoy+ZD4U/iK+NP4J/m3+er6RfyM/dn+YwD/AV0DSQT3BHsFuQWV' +
  'BSQFhgQHBG4DjgKGAbgATgDP/wP/Lv55/e38f/wf/N77HPyP/P38bv3s/aP+jv83ANUAbAHhATMCkALpAvQCwgLOAv8C/gLLAosC' +
  'gAJ7AhQCbQH/AJYA7v9s/0j/ff/G/w8AOACUANIAXQHoAdkBrwEkApwCpwKaAnQCTQLzAccBowFfAQUBFwFVAYcBuQHCAacBawF9' +
  'AX0BOAH9ABMBTQFNASkBPAGKAdABFQJ/AvICFQMgAyADGwPbAn8CGwK/AZoBaAErAfwAvgDNAMAAkwCAABsAxv/n/xwAEgD//+f/' +
  '7//Y/4z/gv9q/13/YP86/zP/LP8P/+v+qv5e/kj+Df7E/Yv9iP3L/ez9u/2N/bH9u/3Q/eT9sP3E/bv90/3o/TX+cP6E/pb+jv6z' +
  '/qn+tv5o/ib+Df41/k/+Xv5x/pj+cP5A/ln+oP7V/tH+mP6C/rD+zf4F/3X/z//c/7j/IvsG/6IKqAl3+0j3NgDmBwsC5vuq/FwA' +
  'h/8H/Yv9ygH2Af//9v/MAW0AI/8D/0wAlwBqAEX/r/4lAGUBKwDx/wkAZ/8w/v/+KgC9AFkAWQBlAPv/8/8qAKP/Tv77/SH/EABo' +
  'AIX/m/90AK4AGQAxAOL/lf/8/i3/FQD9/zb/t/8FAJL/H/9b/1gAbv+E/hv/y/9g/9P+ZP94/8b+n/4Q/x4AQQCn/tn9Of8uAb0A' +
  'dv4K/rr/WQCf/1D9B/7YAf0Al/zG+/v/wQLE/3L8Vf1zAZQB5/0x/YMAkwG+/7L9P/41ACgBYwCR/qz+9gBeAhwAIP7G/1UBtf+b' +
  '/rz/SAGc/6b95f49ArEB3f0W/RYAeAFTABv+s/75AJ8A8P6a/msAXgEQAPr+bv/yANgAKgCT/1oA/ABkAJ/+GwDPAUEArf5T/4AA' +
  'qwD8/m/9kv7XAM8AFQBn/7D+Gv9gAcwAE/8W/lb+vP9Q/5X+MAC5AVz/u/1T/zACiQFu/mP+GgHkAHb+Nf60/4ABngD3/RH+vv+z' +
  'AMj+xf1AAioDcv8z/br/pgN7Acj8rPuPAHcFtALI/N/8LwI3BWgBxftl/XcDtAMl/vr6Wf/WA+sDgP+O/iUB8gL9AR4AiP6D/ycC' +
  '+QAL/mL9JQDiArwB0ACSAL8AYAGeAHYB5gEWAJL+4gB6A5YBO/9P//EADADAAFkBygFyAFH/pgFPBUQD4P/I/X//HgKkAfr+gf+r' +
  'AKkCcgIkAToAiP+1/xYDPAVyAEv9xAHSAsv/w/6HAOwCmwAH/8YAFALfAZ0BmgCt/ZX9/gCuATEAPAA9AnMFewFC/Rn/NASDAmr8' +
  'h/wcA9cBPP08AHMEBAT9AJ3+LAEWA10BhvwG++T/WwLoALj9dv08AZoFOATj/mL81ADDA93+GPsI/BcAQASKAxQAxf1NACQCMACn' +
  '/X3/vwFJAjb/aQDvAhoAHf2B/x4D4wMO/4T5ZPytBIcEs/2Z+8sARQUpAyv8Wf1eAFwD3QH8/FL8gAG9BDwBMP1V/nIB/v9W/Nr9' +
  'iwCWAnwBpv/8/i8AMAIUApL+6fpx/bMAKAKMAX8APv7d/8YDcwKY/bL9u/+2AYX/UPvs/toC0AJ2/5L+jgMfAz//YP4GAHQAaP4v' +
  '/kYARwAJ/7T7yv08BdMECP+H/T8B+QPNAKj7k/3K//oANQCF/k78P/5TA60ELAEE/W3+YgTQA+T9gvwRADkCD/+4+zz9cANrBgQD' +
  'gv3H/N4CBwWGAPj77fxgARgBRf+0/jUAmgPUA5ICvgHs/3j/oQE7AR3+8/pr/DECwANEAAz+ngDVA/AFagP//3/+PAC0APb9VPwJ' +
  '/s0CVAIF/QT+XQNCBsIBR/7g/oUCHgQy/wD7vv2eApkBMfxL++n/jASTA5gAIf00/hIC/gE9ACX+K/74/tIB/QLR/zH9ov1nAQ0E' +
  'VAGy/Pb7AAAKA2IBh/3f/pMB7AH7/1n+Rv9AAkMDO/61/TX+Bf9CALT/9v1r/hoB5gLTABL+wP9OA0oDbP69+0z+WQGR/2f7Ovya' +
  'AHoFWgTn/uX7Ff5BAl4DrP72+sv8WQFxARv+vPyH/swCGATsATn+kfyl/gMBuQAT/sP8gf2V/60C3wFo/+H8Rv02ArkFowHD+8n6' +
  '/v8VBCsDm/3X+j79SgOpBJX/iftY/SACeAK7/n78Fv5IAm0DuQCn+377JQFQBTECd/yy+/cA2ATQAeD85fuM/0EC3AHJ/xD/SAD/' +
  'AND/hf8/AIoAbf/v/QT/wwAuAef/yP+KAG4AFgB2AHoBHQK9AK3+BP5s//MBeQHA/kL9ZP4vAIUBjABp/+n+gQG7AnMBN/9m/Wb+' +
  '+/+SAA4Avf4M/1kAgAESAT7/Y/7M/w8C+gGhABD/W/+3/3//Kf/q/mz/KwBm/1/+f/53/6MA9wCqAPz/UgCvACsAcP9ZABsCHQHl' +
  '/gH+gv5v/wwAxv8y/1r/w/8xAK4AJ//q/Rn+Y/92AJUA0f94/mL/IwGrAi4CnQGGAZIBfQCu/1sABALJAET9Hvs2/IH+O/40/Lz6' +
  'nPvH/lgBOAG3/x8AMwP+BTMHkQWjAx8DWAQOBQgD+f4H/Pz6gvqk+Mz1YPSk9dX44foa+zj74v01AyQIfgpSCgULNQ2CD9MNnwlW' +
  'BVEDrQE0/sv3U/KW7/jup+2g61nqde2c82P72QEqCI4ONRVgGr0b/hhUFNsQEQ3TB8IACfry9DXykO9m7C3nO+SX5c/rLfNS+dj+' +
  'qQT7DPEUPRrEGgsYvBWuFDUSsgxUBb3/4P3j/CD5i/Im7EfnYuSR44/kROny8IT7/AQdDToTDhm9HLMdWxq+FVUQVgy/B/4Cff5u' +
  '/JH7APqb9avvZOcR4ZbeTOGu6LHxzfuFBNcN8xX0HHMfDB6MGecUmhAXDCsGbQAX/VP9fv4k/TD3C/Au6APhR90c3lzleu+b++AE' +
  'nw3dFJocNCA8H1UZbBNZDiALWwZjAXr97/34/8MAavye9Gjs6eLd20vZvd4/6rv3PANZCwMTOBpMIN8fDhp0EroNrQpnB14CS/43' +
  '/hkCVQXrA4r8g/L56FXeCdcG1kvfcO1o/N4GTg8lFwEfMSLrHi0Wkg63CVoHQgP9/rD8SACjBfgIeAVz/Z/yoOhf2wnTqNFw3dXt' +
  'K/8JCicTzRq7IkUkmB4SE3YKnQXQA/b/nPxL/KcCCQpdDqsKiwJi9lnrD9utzjzKc9Ua6Iv7RQnRE6EdLiYOKO4gFRQ7CSMDGwCn' +
  '/MX52PpjArkLpxE1EGMJ8f2Y8EzgAc4UxUTJnt0m8wgHpBJuHswmSCxqJscZOgooAcL70vm59lL4n/5IC+UTVBelEVQJwPsG7cHZ' +
  '7MWbvSjGAt8N+MAMSxljJSwutzB5JkcURgLc+GT1UPWO9Ir4CQJ8EHsZUhseFSMMnv/p7nLbPMVOutTAUdkV9fQLchsbKCcy9jO4' +
  'Kd8VrQLx9lby9vCS8N/01/+UD0IbBx7iGZ8Sdwlx++nnEdLZvNu3kMQ54T79QRSUI00wHDecM2ojWQzo+D/u4Ory6s7tavZlBa0W' +
  'BSErIm8cSxVJCxP+zOk61V7AT7emwMzY9ffpD/EihS18NaExtiRrDST5suuE6OzoQO2p9GwD0BSvIp0lySCnF44P2gOI9hfjbtI0' +
  'wV67L8W83ef9WRYSKOIuYDI4KxUd7gXX8fflNeXt6PLvePmECQ4bHyjwKAkhcxV0DHkD9/gB67jais1kwG7Dv9J28QMNHSBZKPoq' +
  '2SnqILIPY/ky6fjjlueY7jn3lQN0FKEjfioJJRsatA8CCfABAfck6njceNOdyIDGlNJy7PUL+h2CJpAkTyXBHm8T8fwp60bikOZl' +
  '7Q729P/BD60fbimuJi0d/BLJDDQG2/3F8bLoOd5B1gHHnsYI1TX14RH2HjUimyGBJScf5g8Q9hXmnuFE6M3tzfQfAB0T/SNIK3ol' +
  'wBtUEwMOUAbp/Jbywuy55Rzcbsz9wl3Qh+rJCwAYuB7RHUclFyOaFjH+H+rz4pLlQerv7pH5gQzUHxgqhSdvH6EXoRENCp0AvPgq' +
  '8+PuPebN2d/L38VT1sPsfArQE5wczx0bJXQiPRXa/5DstOW85PfnNewl+HgLiB1FJyYl5x9GGqIVsA0iBC787fcQ8wnrqt200fnH' +
  '6M0a4Nv3sw3qFVEf1CFOJwcedw+5+s3tUucY5a3lkOr0+UoNnh2CIxgiXSAlHhca0A9vBdX8XviE8ZPnONti0l7Mj8+732nzlAu1' +
  'FMUeISDeJKoe5xJGAQnzm+ra5WPkuOZE8uEDzhSjHlAhpCKKImYfGhbBCtIBLfyW9p3sUeI42bjWLNNH2JXkHvafCNgPTRfpGAMf' +
  'FxwhFcoHT/x09JjtV+kh5/ftivrdCEoTzhgpHkEi5yPgHpIVggsvA/n6Te/94ujYV9S50WDTJN4i7Dn/6AcSEb0VjR7GIRUeOxRy' +
  'B8D+FvW07dLlHOZw7bv55wQvDlwXsyBVJ2kntSG/GK0P8gQY+EboEdyS0/jQmc1P0o7cnu0R/lYHYhFpGAEkqSV+ImgWIAyhAtX4' +
  '1e7S5GfkVulg9Hz9fwdJEtId4CbkKFcm9B4sFzwLvvzS6yDeTNV50FbMgM291jTl4fX+/wELqRTuIHsmECXZHCAUvgxGBN35su4O' +
  '6c7pGe859Y37hAQQD+cZOiBRIhIg4Ru+FDYKKf3n7wnmrN6D2HXS0tKQ2f/k7u+F93wBHgyEGHQeMx8PHCkZFxZSD4gFWPpt9Fny' +
  'evMK9Kv15PrmAo0MtxKwFjIXxheWFeQQzgiq/gT2Qe2k5QLcF9dU2Nzd/OUc6n7yk/vhCVQTChlgGksb2hzbGZATnghQAU/8W/qd' +
  '9sDzF/QY+XsANAaBCrINAxKqFGAUtw87CfkB3/pJ8i3pQeBr26Dcs96845Xm2u6i+N0E9Q2gE0AYChvTHfQa9RVrDUYHzQEu/QT4' +
  'BfTL83L2ivtz/zIEhAgFDrwRNxN+EZkNywjVAhT8Z/OI6iniHN1c3XPfEeS055LuUvjeA2UOHRR/GGEa4hwNGygWpg3SBSMAlvt/' +
  '91nzhvLg9Nv6aADaBVUKCw92E1UVZRTKD2UK5wOu/bn1QO2Z5Ize79tl3jPihufP7BP0U/4lCNUQcRRjF+AXxxjvFUwQfwiDATP9' +
  'r/lE9/T07fVJ+Sb/lwQwCUwN3BBWFOQUGhP8DV8IbQJz/PP1ne566NriZeCq37TjSug27nbzXvmOAZAIRQ/2EMsSHRKuEpMQdQzZ' +
  'BlEBqP45/Ff7wfnM+nz9MwLoBlMKig2lDywSOxK7EDUMVwcnAg39zvfw8Rntk+hg5RjjOuNO5+Pr/PGo9QP7AgGXBx8Nvw4jED8P' +
  'YxDaDlMMHwdRArL/9P1u/b37JfzH/UkCoAYGCooM6A1aEPIQnBD6DNQIEgT2/3P7KvY48XHsRekh5krk8uNC6KXsBfOP9h/7ZgFd' +
  'BwYOow8OEYAPvQ9tDt0LMAfYAdP+9fz7/Pz7K/w3/ckANQUeCbMLUg3KDnERwhHFEPAL4gavAsb9C/lZ8rHtd+kL6NvkH+Tq4Yjk' +
  'Wu0F9MP+ZQCLBVAKexDjFUEVchH1CwEI0ATWAWj7B/c989n0Ffjh/B0CBQilDyYW0h18HtUdIxfsD98Ik/+t9+3uZ+iz5rrlZOZw' +
  '5arjD+UP5+jxR/3hBuoMuAu7DfAOJhA3DWgFm/x298P1svf+93/4Xvqg/8IHlw5ZEukS9hGKERUQaA1+CBoD9ABV/wEC9wC5Ac7/' +
  'uP92/579+vgA8MPkXtqI1UfYv+Y09OkC5QlDEPAX3xwWHiQVkwf/+XrxVO4l7XTs1u1f9D4AKA4pGDMcZxs6GO8VOhFDC2cCjvpb' +
  '+F/5W/8iAi0FSwUfB8wHYQa0/jPx2eAB0jzMe88m4Vzz1gUgEGMX3B4LIx8itRXhA3bxVOcD5crnaOtP8En5JQd+Fg0gmCFXG3QT' +
  'KAzLBtYAHfux9Z/3dvxeBxUOTxLEEYcP/gyWB9D+ae/l3l/N3sXaxfrW1u7VBv4Y0R5sIzwiLiF9FqQFPfD436badN8c69b11wD4' +
  'Cn8XHSGvJJceQhLZBEj7Yvd/9hP4WPrIAF4JvRMcGtEa8xXJDTIFWfxf8uzlONnYzKTJgM0t4vv6jhNIIcAhuR0vFvYRbQj++3nq' +
  'j94e3N/l7fUkBM4NERJzFo8Z4BpSFSMKvvyL8lLx+PV2/xMH3gx9EawVuRlEGekUwAqNAKj2u/C56vfkTtwv1bvS4too8IgGTRpI' +
  'HdoYjA6ICVAGZALO+PXrd+Nl5N3wPwAVDXkRhhFuENQQ9RDuDM0EKvot85DzUvo7BrIOFBW6FQsWkBTPEnsOaAc6/9v2nfGJ7Jzo' +
  'xuDD2YzUK9oL7G8CHhdfHIkYJw2iBgMDsAGO+2rxz+dR5RPu4PxSDJwTdBQ3EBwNWQtFCnYGx/8z+I30eveDARINUBZMGckWkRJi' +
  'DisMCgmdBHD9KfZF71nqTOSZ3ezWt9ac43X3rg8QGzscSRERBwwAl/7j/E/39u715xDqafQcBSoSrxiuFRcPQAh8BaMEbQP7/hL5' +
  '7/W6+fgEOxLLHFYdHRi7DYgHMQQPBekDtf/j9xzvhujP4Y7d9Nc83BLnU/uODkMZjxmiDwsG1f2J/GH6Xvjw8f7tY+4D92EEKRGg' +
  'GN0W7w8MBhYByP7MABIAJf+s/GX/iwbvEYUb2R2sGC8N9wMM/kD/tABsAcn7PvM36HjeSdi71ivhdu+kBFUQuhavEJUJbAGe/on9' +
  '/Psd+Krxn+4o8Dj6iQYzEwUY7BXFDL0D9f3b/XYAYwIfAqUAFgIuB3sQsRfRGu0VVg2zA3/+n/27//wAf/309Xbpcd6l1AjWKeEf' +
  '9VsJsRRDFkINQAQL/Nz75vuI/Vv5v/QX8JLyAfshCOAT0BiCFVoLeAEz+zL8/v/dBPYFUQbzBRkKbQ8iFrQX8BTRDJQERP5O/ED9' +
  'nf3q+o/yg+aW2dvRT9c2533/RBE9GjoUcwmI/KL3N/dB+0j8MPoE9TnyWfX3/ngM2RYTGrMTxwgV/nv5xfovAH0FngjoCYoKPg09' +
  'ENwTtBMcEXgKEgT8/VT77/m9+BD14uw94hnXWdbn3x71iQkhF/MWZA18/9P1JPOi9ov7j/2K+9b3Ave5++kFOhEAGMoW/A2iAuL5' +
  '8/fk+9wDpQrzDjcPdg5+DUsOTg9/DykNDAikAWj7WfeA9HnySu3X5e7bvNkc4AbywwRgE7IVCQ/3AZf3XfIq9GX4RPys/I37/fpE' +
  '/lsFhw62FDQVug4YBej7H/j2+ZUB2gnbEOoSGxKJDicMegrgCmwKqAjYA8X9Mfcq8iXuweke5FXeHt/35qT2iQUUEJcQewqL/2f3' +
  'HPOp9An49Ps2/b79Fv5LAQUHSg7PErUS3wxnBHX8Kvmd+zwDUgxRE5sVQhNUDsMJeQd8Bw4IKAd3A2T9zfUZ7yXpneQo4MLfcuVp' +
  '8Wr/NAo3DjULkQNX+wj21/Sx9gv6ovxZ/hv/7wBKBOkJwA5LERoP1AlkAu/8FvtD/2cHfBAdFkkWiRH0CucFLwQzBZMG3AWqAd75' +
  'DfF36Pzhkt3o3vTm9PMNAYQJdAvqB3QBdPvk9033VPiB+hL8rP25/jMBwAQHCu4Nyw+LDTkJOwOZ/+v+TQO0CaEQwxNWEw4PmgrI' +
  'BrQFUAVrBTQDBP9092fvCOb13qTagN9D6s/5gwX4C3YKZwW5/ez4WfaU96r5vPwE/vP+Ev8pAcYE3AmODQkP9QyoCMYDMwFkAkEH' +
  'dQ0iEjQThhDeC1sHpASeA9gDdAMhAWv7wvMN6iPh2NoO3a3mivVFAq4JpAliBaj+AvrO9wn5TvsY/v7+/P4Y/uX+oAF9BvoK3g2L' +
  'DYgKSQZWA44DMQevDCgRmRJdEPQLTwc6BNsC8gK8AtcArvtD9C7quuDG2jDep+iB9zIDbgluCK0DEf0S+d33F/o1/fj/ZgBU/8r9' +
  'Kv4MAbUFaApGDVgNgQrkBkkEJQXJCB0OuRGTEpAP+wrwBasCGQE+AfUAcf7m+B/w3eVa3TzcheO28N/9igaWCJsFfv9n+gz4mfkE' +
  '/c4ATAKyAVD/Df7j/ocCJwd7C1QNaAxMCVoGjQX1B1sMgxBAEp8QZQw9B9wCRACL/zz/bf0U+SnxNueu3nfdK+SU8Of8VwXEB10F' +
  'v/+6+k34tvlZ/YUBoANdAxQBP/8w/8EB8QVgCu4MugyCCjQIzAfFCRcNvA9jEG8Owgo+BksCgv8b/mv8ufkw9EXsuuP73ynjSuwz' +
  '9w0AmQT8BMMBc/0k+qL5jfsj/yUC0QNeAywCOQHOAdUDDAfgCUoLLwt7CiwK7gpEDFcNiQ1+DIEKuAeyBK8BD/+9++b3QPKR69vk' +
  'AeN65lzu0PZn/cQApgH1/7H94/vS+wz9c/93AeQCHgP2AskCVwOWBJcGnAgNCusKWAvKC0EMswy3DE4MMguUCTwHZgQ7AbT9iPmm' +
  '9MHupOgL5dPmV+yG81b5C/31/kX/VP4s/Zb89Pxn/jcA7QH6AmwDgQPgA5gE/AWZBx4JUgqIC4QMOA1YDfcMMgxJC+4J/QceBawB' +
  'ZP2u+DPzTO3C5/XlG+n+7hT1hPkJ/JP91/1h/cz8zfyD/Sr/2QBaAgcDSQNpAxwENwXIBkQIjgnDCiAMRw0EDgkOVw03DLoKywgU' +
  'BrACYP6F+SP0WO4U6f7mq+nJ7lr0Z/gB+8X8oP2E/UH9BP1W/YD+DQCRAX8C6gI8AwkELAXMBloI0gk3C6sM2Q2fDp8O5g2bDLQK' +
  'OwgGBQAB7PtL9j/w5eqw5wzpIu0E8gL2APk/+xv9rf23/Yb9v/1//gMAXwGMAvICOAOpA74EQwYSCLkJQAvODBMO+Q4GD2MO5gzx' +
  'Ch4IwwRyAFr7fvWC737qTeh56pjuoPLO9bv4lvvo/Vv+yf1M/cD9Dv/aABMCuALKAhID2QMaBakGiwipCsQMjg5+D54PxQ5GDQQL' +
  'TgjiBCIBZPwX9ynxO+xj6eXqTO678V/0Z/d9+mb9N/7n/ZP9S/5p/+QAxgFwAtACbgNNBJkFIQfyCN8KwAxYDkoPSw9IDnkMDwok' +
  'B7MDjv+v+mr1RfBN7Cvrau1i8M/y+PSt9+b6VP3q/b79OP4y/2cAQAHqAWwCKAMXBHgFGwcgCSMLCw15DkYPCw/rDf0LnQm8BogD' +
  'qf9n+6f27fHU7Trs1+2A8Mzy2/RR9z76jvxc/YL9G/4A//z/rgBSAfsB+wI0BMQFeQeTCcALvg0WD6oPKQ+6DWwLlghEBcABvP28' +
  '+X/1uvGH7t/tZ++Q8V3zTvWZ92v6a/xr/dv9lv4+/woAlwBXATMCiQMhBQQHzwjHCpoMHw7iDs0Orw3BCzwJVQYlA4X/yfvP9yP0' +
  '7PC/72LwwPHz8ln0JvaJ+If6zvu2/MD90v7+/+gAzAGqAvQDaAUgB8QIkQpODLMNYQ5JDi8NRAu4CM8FmwI//+f7rviu9UbzdPKv' +
  '8lTz9PPe9E32IPiv+e36Dfw0/Wj+pP/YAAUCXQPxBMAGdQj6CUwLTAy1DJAMywt+CqkIagbXAyoBkf4M/If5Cfde9cT06/RH9Zr1' +
  'A/bm9gr4QPl8+sj7P/3j/n8ABQKPAx0FrAYLCBkJIQoaC8ELvAv0CnsJqQeWBUYD4gCQ/lb8Mvpe+Dj3t/aK9n72n/Y59y74T/lY' +
  '+k37YvzM/V3/AQGPAhEEjwULB2IIjAliCr0KpQoLCgIJnQfnBe8DxgF6/yT91vrK+CX3Q/YW9o/2Wfcu+Cr5gvrt+zP9RP5Q/2MA' +
  'mQGoApkDZQRjBWgGWwcGCFgIVAgZCHwHVgazBMQCqgCJ/qr8K/vr+cr49fes9+v3q/id+bT65/sZ/Uf+hP+sAJwBWgL9ApMDMgTP' +
  'BFYFqwXYBekFzwVbBY8EfQM9AvoAtv9w/jL9C/wd+276/fnn+T366Prd++H82P3f/vj/BAHiAYAC/wJkA58DrQOxA70DuwOnA30D' +
  'PwPoAmgCxAEAASoATP98/rv9Ev2e/HP8dvyZ/OL8ZP0c/uz+t/9vAAoBoQEgAn0CqQK4ArsCrgKXAmYCGwLNAYcBPgHlAHkADQCv' +
  '/1v/Dv/D/oP+Sv4P/uz97/0f/mz+wv4S/2n/xv8yAJYA3QAWAUYBcwGUAaUBmgF2AVEBKwH4AL4AjwBqAD0AEwDu/8f/nf93/1j/' +
  'Pv8o/xL/E/8v/1f/iv/D//3/MgBtAK0A7QAjAUABRwFAATMBKwEmARQB8gDRAL4AqACCAFAAGwDq/8P/r/+m/5b/i/+N/57/sf+/' +
  '/8f/1P/w/xcAOABTAGgAgQCXAKkAvgDPANwA4ADYAMwAvAC4ALYAswCiAIwAegBvAGQATQApAAYA9P/o/9v/0f/N/9b/8f8SACYA' +
  'MgA7AEsAZQB6AIEAfwB9AIIAkwCiAK0AqwCgAJUAkgCNAIEAbgBXAEcAPAA0ACYAFAACAPn/7f/c/83/wf/B/87/5P/7/wkAHgA4' +
  'AEkAVgBbAF8AZgB1AIMAhwCJAI4AlACWAJUAjgCAAG4AVgBAACkAFwAIAP7/8v/s/+r/6//s/+n/6f/r/+v/6v/r//D/+P8IABcA' +
  'JwA0AEQAWgBrAHcAfgCFAI4AkwCTAIwAgABvAGAATwBDADQAIgANAAAA+//5//T/7f/n/+j/7f/1//z/AwALABcAJAAvADsASABa' +
  'AHEAhgCYAKgAtAC3ALsAugCxAKYAlgCEAG0AVgBDADAAGwAGAPj/7v/o/+n/6v/p/+r/6//0/wIADwAdACsANwBAAEkAVABfAGgA' +
  'cAB5AHsAfgB9AHsAdgBuAGEAUgBFADcAKQAaAAwAAAD1/+//6f/k/+X/5v/o/+3/9P/3//3/BQAPAB0ALAA8AFAAXgBsAHgAhQCO' +
  'AJEAkACPAIoAhQB6AG4AZQBbAFEARwA9ADQAMAAyADMANQA5AD4ARgBNAFcAZQBxAHwAhwCRAJ0AqQC0ALwAwADCAMMAwAC7ALMA' +
  'qgCfAJcAjwCFAHoAcABqAGQAZQBhAGEAYQBiAGMAZABoAG0AcQB4AIEAigCSAJ0ApQCtALQAvADHAM0AzwDPAMoAxQC9ALQAqgCb' +
  'AI0AgAB1AGsAZQBeAFoAWwBdAGIAZwBtAHQAewCFAIoAjgCTAJYAmQCcAJsAmQCaAJkAlwCZAJgAkgCLAIQAfQB1AGkAXABQAEYA' +
  'OwAzADIALwAvADEANQA7AEAARABJAFAAVQBZAF0AXQBcAFoAWQBWAFUATwBKAEUAPgA5ADEALAAkABoAEgAMAAEA+P/y/+n/5P/h' +
  '/+D/4v/j/+f/7v/3/wAACwAUABgAGwAeACEAJgAmACIAGwAXABEACQADAP7/+f/0/+3/5//h/9n/1//S/83/zP/M/8z/zP/Q/9T/' +
  '2f/c/9v/3v/i/+f/6f/r/+r/6v/p/+b/4//c/9b/zv/H/8T/vf+3/7T/sP+r/6X/o/+g/5//mf+U/5P/kv+T/5X/lv+a/57/pP+s' +
  '/63/rv+v/7H/t/+2/7P/rP+n/6T/of+e/5n/k/+M/4b/gv+B/3f/cv9w/27/a/9s/2//cv90/3L/c/93/3n/ff+C/4b/if+K/4f/' +
  'gf9+/37/gP+C/4H/fv92/2//bf9s/2z/Zf9e/1j/Uf9R/1P/VP9X/1n/XP9h/2f/bf9u/23/cf91/3n/ev97/3f/d/94/3z/f/+A' +
  '/3//ev93/3b/ef97/3T/cv9z/3r/fP96/3X/c/94/3v/ef99/4f/jv+M/4j/hv+H/4j/j/+V/5b/kv+L/4f/hv+I/4j/jf+Y/57/' +
  'mf+P/4r/j/+U/5L/jf+K/4z/jf+L/4//nf+o/63/pf+f/6T/s/+0/7H/sP+z/8D/zP/D/6r/mv+c/6r/rf+n/6f/s/+4/6X/lv+Y' +
  '/6v/sv+l/47/j/+n/7f/s/+h/5v/qP+1/7H/n/+X/5v/nv+f/5j/kv+X/6f/tv+0/6H/jP+M/6X/tf+l/3j/ZP9x/4L/gP9p/2D/' +
  'ff+Z/57/lv+b/6P/pv+c/4r/e/9z/3r/gP+D/4z/oP+x/6T/hf9t/3X/mP+6/73/k/9z/37/lP+O/3T/bf+U/7H/lP9k/1v/hv+k' +
  '/5z/jv+u/9n/2f+t/6H/rP+p/37/aP9+/5//oP+R/6L/xf/K/67/ov++/+z/+f/o/8n/vP+//8v/2f/s/+P/z//J/9n/4//h//X/' +
  'EQAkABoA9P/j/+v///8EAOz/0v/J/9z/8//9//f/+v/+//r/9f8FADsAZQBVABkA5v/m/xMAGgASABIAHwAXAA0AIwBQAHkAlgB9' +
  'AEAAFQApAEAASQBLAFAAOQAVAAcAQgCcALwAiABoAEoAIQDl/+z/LAB9AIsARAAHAAEAFgAbADoAfQCzAKIAXQAyAFwAqQCqAHEA' +
  'UACCAJ4AkAB5AG4ASAAqADMAfQCtAK8AewByAIIAeAAuAPr/EQBlAH8AYgA+AFcAdwB3AFwASgA7AG8AtgD/AM4AowCUAOAA7QDL' +
  'AI0A5QBFARsBkAB3ALMA6QDVALEAqwDMAKwAkgCzAPEA7QDhALkAmACAAIEAnwCLAHkAbACGAIMAnQCoAPQAEAHpAKwAoQCaAI0A' +
  'kwCNAKQApwCRAHwAjQCVAEIA8P9iAP4ADQGjAEcAawCZAHsA7//q/3UADAHqAHkAUQCuAOEAgwAUADsAnAClAEkAHAA8ALwAzwCl' +
  'AFcAhgC6AMkAhABiAJkArABeAAMAGABjAE8AKgAUABkAEgDl/+X/TwCaAF0AEAAmAEEAMQAFADAAIwAWAOP/KgBkAFYA5P/7/zgA' +
  'XAASAP//GgAyAO//2v/k/zwAPwAvAC8AKQDI/7j/PQCdAIcAlQBkACQA7P/T/wQAVwB4AFUANgAbACEAPAApAB8AIAD6/9b/AgAh' +
  'AHsAgACAAEIAYgBPAD8ANACSAH4AJgALAD8AiACEACoAGwBvAJgAFACL/97/bgCTAEMAEQAnAH4AXwAOABwAlQDoALEAWgD8//z/' +
  'NwBXAFwAWABqAGQASAALAFAAtgD/AJEAigDGAIYAz/+l/xgAyQDZACQAzf9hALEAPQDY/zgA3ADYAAEA7f84ALUAdgBgAFoAqwCZ' +
  'AFUAGABZAGIAGgDC/w8AXgCkAG4AYgBbACUAvf/f/0QAUwA0AP7/BgBTAMAAbQAxAE4AbQAhAPT/9/9vAHMA9v/7/0sAjQASAMP/' +
  'NgBNABUA4P8GAEIAGAC5//L/QQBlAL3/g/8AAGYACwCk/7X/LQBDAMP/5v8EABcA5/8CAN//wv+2/zYAQACm/3z/FwBxAAAAu/8r' +
  'AKYAUACJ/1v/EACfAC8Ayf/B//n/9P+v/9v/HABgALj/g/+U/zAAYABpAD4AJgDt/xsADwAJABMAGAAAAC8AJAAVAPf/BAAdACQA' +
  'QgAfAD0ARQArABAAIwBZADYAMAD0/yQA7/+d/8D/UABfAGMAWQAxACwAJADS/6b/0f8NAOD/yf8GAFMAogDl/4f/y/+cAGgAzv/Q' +
  '/zEATAAiAC4AcQBxAAUAzP98AK0AEwBn/+f/qQB6AKz/sv8kAKgAPAC4/5X/6/8uAPX/KAAtADgAGgDt/+n/HAAoADMAGADu/87/' +
  '7//L/7j/9f90ACYAef9t/wcAFgDE/6b/gQCnAA8AX//z/6cAUADL/wIAZwBLAN7/3v9lAG4APQAcADcAIQABAAoAHwA7AA8A3P8D' +
  'AC4APAAPAPD/AQA8AG8AIQDp/wQAMwA+AAIA6f80AEYAEQDX/xEAaAAVACMAOQCkAGkAQQApAC4ALAAVAAsALgBpAAEA8v8oAEAA' +
  '1P+i/6n/EgBRADYA+v8aAAoA3P/6/x4A+v8CANf/CgDR/wIAFgBkABEABgAjAFEACQDA////UQASAJ//3/8pAE0A8f+7//j/DgAM' +
  'AAUAQQC9ACMAif/+/1YAMwCK/xwA3gAKAVwAqP/B/1kAPwDd/6r/KgCDAHUAsf+e/0oA5QBsAAoAy/87ADQACAC2/w4AYQBYABsA' +
  'oP+y/xMALwD4/7z/CAAgAAEAHgAaAEIALgAWADAAYQBAAOv/KwB1AIsAOQBeAEgAUQAEACwAkwCvAPf/xv8FAGQAHADo/zYA1ABi' +
  'AOz/rv8+AI8AhgBuAIEAUQDR/+f/YADm/xQATwA4AND/iv8FAGoAcAD5/8j/1f/T/w8ANAAuAHgAYQDo/9f/BQCHAIoAQgCU/9H/' +
  'HQAlANL/cwCcACEAu//l//z/7v/C/yQAaABQAKX/m/9AAH4AEwDR/zIAZwBfAPn/1//0/1YAdAA7AC4ADgD1/wAAWwCBAKoA2gDz' +
  'AHsA7P/M//z/YgBJAJUAnwAbAHH/1v+TANcAowAWACUAewAsAHH/IgCtAOUAFADB/wAAYwBwADkAOgDg/6P/pv/Y/ykAYgCFADwA' +
  '8v+R/1//xf88ABcAof+w/wwAiQA4AA4AVwBpAOz/qv/8/0sAZABPAAAA5/9PAAsAGwDN/xkAVwBJACIA3/8tACMAqP+5/wEAIADB' +
  '/3D/1P/g/8r/mP/P/3EAUwDC/3L/+v8JAO3/0f8/AFkA3v95/+j/EgDA/8j/RgB5AOX/qP9OAKsAFQCq/x0AlQAkAK7/zf9EAGMA' +
  'AADe/18AVQA7AMf/CQAIAJcAmQBuAEwAYgB/ADEA2v/7/0kAYQA3APT/GgAuABQAIgBoAFcAggBeAHAA9v8mAEsAowCIAEgADwD8' +
  '/xMA6P8RAH8AgwCFAAQAEQBoAIMAAAAzAAAAjP+T/+b/EgBfAKUAZACl/7P/yf98AEIA9//y/0kAXAC8/+H/WwCNAEUAGQAyAPX/' +
  '8v/g/4YAjwAbAN//IwBRAPr/qv/6/zwA3f+Q/4v/AAAOAFAACwAaAC4ACADk/+P//f8rAAQAtP/N/woACwARAP7/vP+l/8f/6f+u' +
  '/6L/MAB5AEAAu//i/2MAZgAKAMb/SwBFAM//pf8SAE8AhABZAFsAZAAyADYAGADn/9n/PwA9ABIAIgAiABcAAwAkAFkALwD5/+j/' +
  'HQAMAMH/xv9FADAA5v+m/xIAXAAjAPP/6v97AG0AMQApADIAEwDK/wQA8v8FAM7/HgDJ/8//uP+J/43/zv/c/+D/9f/T/53/j/+M' +
  '/+D/JwDc/yj/bf+R/77/pP/1/z0AJACb/4H/6v/n/9n/1P/y/5z/f/++/zUA+f/G/73/nf+R/3f/5f+DAGUA7f+k/8n/QgCX/17/' +
  '+v+kAF8Axv/N/0oAkwBnAP3/9P8YAPP/nf+v/93/jADPAGQAyP8YAIAAYwAWAAYATQAzAP7/wP8cABwALQBAACIA4f/J//7/JAD3' +
  '/x8AFwD4/9H/+/9IAFwA6f+L/+n/PABDADIAiQBcAOv/xf8iAGYAPADV/xIASQD9/6b/4v9IAEMAuf+t//H/5f/J/xEAmACKAOv/' +
  'k//g/w4AiP+1/48ATwC+/5b/FAAmAMf/tf8ZAAsAYf9f//X/EwDF//7/JQAmALP/wP8kAAUAjP+z/0QAHACv/+f/ZwDz/27/p//X' +
  '/7D/X/+s/wIAv/99/6j/OQDZ/zT/T/8LABcAnP+W/+L/uf9v/5H/9v8VAMv/Zf+F/wUAQwAkAAQAy//q/9f/1f+6/7v/wP+L/6z/' +
  '8P8BABoAMQAkAOT/a/9m//n/iQBQAL//4f8JANT/s//W/yYAKwDY/6L/av+A//P/VAAqALP/m/+1/6D/Vf+i/+3/KgDD/7f/vv/Z' +
  '/+3/3/8NAP//DACV/6P/mf/O/83/xf+g/6b/5f8OANL/1v/x/+D/mf+O/6X/xv8SAD8AQwDb/33/pv+2/6X/sf/4/xkAqf9k/57/' +
  'CwAIANX/zP+6/6z/ev+S/4z/tf/S/9X/uf98/53/9P/P/2f/bP/U/+r/4f/2/wsA9v/e/6D/r//s/yEA4f+d/8L/DAAzAPz/+f9n' +
  'AHMAAACu/+P/IADt/93/JgBxACYAzf/A/9r/3f/1/w0A3v/a/+3/+f/t/8v/9//4//n/uP/B/+X/KwD//+7/BgDo/9z/EQBBACAA' +
  'DgAeACMA4/+u/7r/GwAiABMAOQA2ANP/kf/Y/xsAKAAaABoABACi/13/o/8tAE4AOgDu/+H/u//i/wsASwA/AB8A/f+t/2z/pf8f' +
  'AFEAAADH/7r/x/+W/43/3P8aAAkAyP/f/+3/AwD7/+v/zf/S/8L/tv/E/97/sf+2/8r/3//m/9j///8LAAAAyv+y/8f/z//M/+L/' +
  '6/+u/3//ef+//8D/0f/A/7b/jf+c/67/0P/c/8T/qP9i/5r/z/8DAOn///+4/2//Y//N/w4AAgDv/wsA6P90/17/2v83AAwA8v/k' +
  '/7n/eP+g//T/BwDk/9b/r/9b/z//yf8/AB4A/f/x/8X/iP+p//n/IgARAAsACwALAPT/8/8SABwAAQDu/wcA/f/5/+j/9P8AABMA' +
  'MwAdABoADwAMACoAEgAEAPX/JwALAPX/+P83AEEADgC9/6//2v8KAP///v8DAPb/q/+Z/8P/AgAcACsAMAAJANf/xf/M//P/EwAh' +
  'ABQA8v/b/9v/CwAuAE8APgASANb/uf/Z/wYAJwAOAOz/tf+0/5n/m/+r/8X/r/+s/8v/4P/z/xoAKQDj/6//tP/e/9f/vv/l/xYA' +
  'EgDZ/+X/8//u/+P/7f/n/8b/t//B/8n/x//N/+//EQDo/7//tP/D/7v/1f8DAB0AIAAMAAgA8P/i/93/3P/W/9z/AQAcABIA/P/7' +
  '//f/AAASAEAALgANAAQAJgAIAO7/FQA7ABsA3P/e/9X/2f/w/xQAHAAIAP//GgAsABkAGAAXAAQAy//Z/wwAOAAqABwAIgAdABQA' +
  'MwBcAHQAWgAxAAwA+//8/xAASABZAFcAQwAkAPX/6v8LAD4AVgBOAEsASAAyACQAKgA/ADIAIwARAAQA9P8NADUATwBXADsAIQAH' +
  'AAgA///4/+v/8//y/+v/5/8CABIADQAOABUAEAD5//X/+f/9//f//v8LAAcA8P/t//X/8f/m/+X/+P/9//7/CAASABEADgADAOz/' +
  'yP/F/87/3P/j/+T/6P/o/+X/2//S/8v/zf/R/9H/2v/r//v/8f/Z/8z/zP/T/+X/5//i/9f/zP/M/8f/0//q/wEA+f/m/+H/2//d' +
  '/+f/9P/z//L/9f/y/+7//f8SABgACwD9//T/7v/l/+L/8v/5////AgAJAAUABQARABsAJQAkACMAHgAbABUAFwAaABgAFwAdACYA' +
  'IwAdABYAGgAUABIAHAAlACQAHAAbABgAEwALAAUAAQD+//j/9P/z//n/AQADAAEAAAAAAAAA/f8AAP7/AAADAAgADwAMAAwACQAH' +
  'AAAA///9/wAABgABAP///v8AAAEABgAIAAgABAD7//j/+v8BAAgADgANAAoACQALAA8AEAARABQAFQAUABUAFwAbABwAHgAbABcA' +
  'EwAVABkAGQAcAB0AIQAgACMAKQAsACkALgAwAC0ALAAvADQANwA8AD4AQwBCAEUARABCAEMAQgBBADsANwA1ADYANQA4ADkANwA4' +
  'ADkAOwA4ADgAOAA4ADMALwAuACwAKgApACoAKAAjACMAJAAkACIAIgAkACUAIQAeAB4AGwAXABIAEgAUABMAEgASABQAFQAVABUA' +
  'FgAWABUAFAAUABMAEwAVABUAEwATABQAEwAUABUAFgAYABkAFwAVABUAEQAQABAADQALAAkACwANAA0ADAAMAAwACgALAAwADAAN' +
  'AA0ADgAQABAAFAAWABgAGAAYABkAGQAZABkAHQAeAB8AIAAfAB4AHgAeAB4AHgAfACAAIwAkACgAKAAsAC8AMAAxADEAMQAyADYA' +
  'NAA0ADUANgA2ADYANgA4ADgANwA6ADwAOgAxADMAMwAuACoAJwAkAB8AHAAXABUAEgAOAAkABgD+//r/8v/q/+L/2f/Z/9T/zv/K' +
  '/8v/xv/B/7v/tP+t/6X/nf+T/4v/gP92/3D/aP9g/1j/Vv9R/07/U/9O/07/Uv9N/0f/Sf9H/z7/Pv82/zL/L/8v/zP/NP82/z//' +
  'Q/9I/07/Sf9L/1L/Tv9Q/0n/S/9L/0z/V/9X/2D/Z/9u/3P/e/99/4b/gv+N/5X/k/+d/6H/sP+3/7//x//W/+H/7f/3/wYADgAV' +
  'ACAAJgAsADIAQQBFAFIAVgBgAGsAbgB6AIAAhwCIAI0AlQCWAKEApACpALIAuQDEAMgA0gDaAN0A4gDqAO0A8ADzAPQA+gD5APsA' +
  '/QABAQYBAgEHARABCAEQARABEQEfARMBJwEbAR4BJgEcASgBGgEmASABJwEiAR8BIgEaASUBFgEiAREBDgENAQkBCwEBARABBQEU' +
  'AQ4BEwETARQBEQEMAQ0B9gADAewA6wD5AN8A+gDhAOYA6wDTAPoAyQD5ANUA5ADeAMkA4gCuAMsArAC8AL0AqgC6ALoAvADKALwA' +
  'ugDMAJkAtACTAHMAvgBoAKcAhgCDAKwAawCxAH4AjACSAGoAfwBBAFgAKQBIACwAKwAzABMASwAZAFMAKwA8ACsAFgAzAAMAHgD5' +
  '//D////j//7/AgD9/xwAAgAlAB0ADgAwAAgALQATAA4ADQDp/+b/x//A/6j/tP+V/6n/pf+l/9L/r//v/9P/3P8BAND/BQDT/+b/' +
  '0f/B/83/sf/N/6T/vv+l/7L/q/+y/67/sv+w/6f/vv+b/9H/mv/Y/7z/yP/e/7b/6/+0/9//0v/W//H/3P/h/+H/0v/l/9P/5v/Z' +
  '//r/5//5/xMA6P8xAOr/GgAYANL/FwDG/+f/DwDM/0cA5/81ADoAHgBrACQAaABAAFEAMQAsAC0ADQA2APP/GQDl/wgAAQDs/xEA' +
  '2f/+/9b/+v8SAPP/KQAFAAsARwD8/3IAPwBhAIYAOQCCADkATABBABgANgANAAkACwC+/9//r/+o/73/g/+3/2//uf+R/9v/uv/m' +
  '/xIA2f9uAPj/ewBHAI8AVwB9AGMAUgCdAA4AlgAeAC8AQQDJ/xsAov+s/8n/gf/g/4b/uf/I/67/JgDk/3kAQwBvALAAmwDaAOQA' +
  'pgDgAJ0AggC2AC8AcwBWAPP/WQCo/+L/qP93/9T/Hf+c/1b/gv/h/3n/JwAGAEMAwgCWACQBcQFlAfAB0wGPAfsBZAFyARwBbwBy' +
  'ALX/kv89/8b+2/5o/o3+ef6N/sb+9P4d/6//CwCKADwBfgGvAsICzANcBOQEtQXzBVYGFAY8BicFtASEA5oBWQBI/rz8CfvR+Qb4' +
  '4vaj9Sr1JfQ99gf25vfs+ZL7ff/PAPEE5AZiCh8Ldw5XEA4Q3BLxEU0SNBGbDwIONQuqCLcFdgG6/SL4ivMe7lLp2uRg5mjmt+QR' +
  '7TvtxvLY+qD9ggTmCHcJdg2aDHoLvAp3DAII1AsSC8gHiA6HCTwNJRCeCqYPhgvjBpkGHf6p+PTyburC4vvo6Nqa5DTnLOJB9krw' +
  '4/38BdYF+A62D0EQyg/cDpQNAwrwDdwFSgtlCygHyxL7Cv8QDBIZDM4MHga9/Zj1OO8F4Erhg9xe1D/kstlk6b7yjPFZCEAFLw9o' +
  'FWARUxYLEo0P1A/FCsEKzQloCMkL+grMD5gP2xGhERYMAgq2/qP2fe0S4MTfJdcy1sfcYth66qTrM/hEBqkG8hWPE34XrBixEkMT' +
  '3w4/C+QKBggmCa0KRgyZD1IR/BJgEkgN7Qhb/b/0I+qL3JPdeNL81IractdL7DDttvsvCo8LXBldGO4Z+Bq/FPUS5g45CcYJHQUv' +
  'B8UJWwlNERkPZxQeEtwMwQhe+uvz4+NJ27TZSs2c1jHUndoj7ZHt0gLUC1YRDB4dHDAdkB0KFigS3w9iBUEIKwOWA8QJWgjsEDoR' +
  'HhTwEqYMwAXm+B/u3N712JbTZMvb1S7R2OG57Qb0+Qr3DvAZoyDSHt4fQRtmFOcPBAqoA6wCfAGSAukI/ApkEWwVgRVgFEINXQKv' +
  '9eTnlNd01AnLecm50izRt+ex707+ihGxFtghSiRWIswfcBiqEcwKJgQ5/6f9Zf9OAh4JoA71FNcYWRkJFuEM0wD48J3iX9LgztDH' +
  'JMe50QDUKut39kAFIxhLHr8lxidII94b2RY8C6YBZwEc9WD8pf0fAf4PZhJrHCAhVx6IGmwOmP7J7Kra6cltxTbBocK90EzXN/Cn' +
  '/rkO2CAFJv4roCnUIvQY0A/sApL8NPWJ9TH1eP+8B8YRRx9UImopcCfpHKUQP/3u5W7VwcBvu7K9dLqR0WfYcfOuCIIUNyorLkww' +
  'ayxFIZUUhgg4+3/yU+tB71bvy/6PCucWECfNLGQx/C+oJLwTRACn5fDOpr0vrp61gbc1x+vd/u5EDkkeMS35N9E1FC5ZI/0P7P+w' +
  '8wTmRuI150fpMgACC5AfcDASNpA/VTZiL+UZ2wJt6OjMQrchqCCn9LJgvYfbbu65D5olTDMxQJ867TRRIBMQy/e76Mjc8daj3DDp' +
  'yPf/EXUmMjZeRo1FlUORNlEiAggu7X7NPrTfpAeYD6qFuDLNmfN6B0wqtjyOQS9FJDrxIpwOf/Uu3KHT1MtwzJvhX/IaCPQuMzgA' +
  'TtZV3kkMRT8tWxAb+VHXVLptp7WZF5RhsD7Dwtv0CRcXhzstSQBEV0MiMi8R/v3n4b7I58gBwxDPM+fPAPcaLzyfT2pVgV0ETII6' +
  'ziTqA77oZ8zLst6cNp2Wk+W3u9Ir5NgYmSEWQkRKfEOtOEsoZAQt7SDXFcDfwP3FrNJt7ZUQPSS6SOJW9FjaWRBJ9i/5G3r8IuDy' +
  'yVizFp4ToUKgQ7VY4kLnWBhTKeI5A0eaPggvlR57Atzi49YQwTjBfcrs2ZvxGRNNLXZDYlipWEtNikikKIwUpvtc4R/KuLwSqRml' +
  'KLB8thbmbO67DuMnjDMqOwA5BCrMFRkEU+QV11DKuca5zsniSvQtEyQyD0CZU61T0ke+PSknNQ+N+k/l5M42w9uyG6zwt0e7p+W8' +
  '81YJYib+Ls8z4zPbJkwQIwMy5xbX0NDsysTTfOYX+pQSpDEiQidKUVK7P/g2kCLbDEn43+gd0MvFNri4sJa5lcWb503wIg70IOgr' +
  'WjCpL0ggsw0p/lDkgNkS0OLPfdhd7OT+HBlTNfJBMkgxS+Q5My/GGwcHN/Oo5AjOCcTWtpC3nLuC1r7sGfZHGCEjCis2LcEqyBKp' +
  'CI/yl97+1gPT89Ti5Lv5agoFJ8g5I0AzRao+US+5IqMR7PxA7s7cjczDv2C8YL1SyofnUu9sCYwc1SZUJ6gsYxq6CQH96+b/2obW' +
  'h9i+3/30agZqGucxkzyHPhg+mjO4I4gW+QVc84XiYtQ4xC6+/b86yr/jA+1OBAMXkSOkI0opNBo4CSj+dOtT3rnatd4U4jv4+AdR' +
  'GcMsUjk6ON02CjEGIL8Vvgca9ojkJNngxszDOsKjz4ziS+33Ab0U7h0pH7wllhXGCC3+PPBF4YvjQ+To6av7JgssGM4owzJZMCkw' +
  'ACpBHdoSXwen8xbjXtTtyPjEuMlo2sHj/fTYBa0U6Bd+HnQZ2w3BAyT6++0J5zHroe1N98wGCRR2HRopvyx+KUEnOiGhFeMKbP3d' +
  '64nbq9HQybrLnNm54Pns6v2RCxQO9Bb5Fc8MgQXXAV32MPHN9Af3p/yUB6sRdhZ0H9AiHCJ/H8odmhTTCqH/9e+S31nYKNKv1Hjc' +
  'LOVg7Yv7WAVHCr0OVA8VCnkFuQJ3/KL5r/un/w8ClAiIDjIT9hYyG9AbQRrDFz4RdgdW+/3uieTR3fPdVOAr5QfrBfT5+n8AMgRa' +
  'BqEFhQMlAjIALP86/yMCpQSyB6gKFA/FEs0VthfYGFsXBxMCDVoER/qO8f/qruez5kfn8ugt7YXxs/Ud+Wf8FP4U/3//dQANATEC' +
  'ngT9BjkJrAtID3QSURUnF/QXWBaEEo0MsATS+3HzNu236f3nd+eR6FjrVe758cT1WfnE+03+bQBcAt0D2wXGB1YJ8ApIDa0P/RHe' +
  'E+sUpRRpEjcO6we5AEv5Y/KF7STrz+kr6bbqqe2+8Ab03fdR+w/+XwCeAqUEPAbSB0kJ4QoYDAoODxCzEVYSkxL2EJkNYwhhArf7' +
  '1fTB783sB+ve6QXrbO0p8DrzDfe7+qT9YwAdA3QFGge0CA0KUwsjDMcNng8QEY4RiRH9D64MmQe5ASb7g/Sf76vszurB6bLqAO3b' +
  '7+nynvY0+nL9ngDXA58GzgjICnMMvQ2mDuYP9RBXEQEREhDRDcYJWQR2/uj3F/IF7mHrcekv6djqX+1N8LLzpfdh+xT/3gKWBn4J' +
  'vAtyDccOgA8nEM0QGBGIEDcP9QwcCaYDnv1D96Dxv+1X6+rp6Omh6yHuO/Gf9E/4+PvQ/74DqQf3CnwNZg/FEH8R+REwEvkRzxDa' +
  'DskLOwdwAQz7g/R47+frjOmW6Jbp2+vB7mfyZ/Z0+mT+kgKZBjEKywzwDmsQVxGdEdgRmRHfED4PBA1SCRoEFP6Y96XxHO0A6kvo' +
  'R+j76dHskvCs9A/5YP32AXwGsgopDpoQ+xGeEn0S9hEnEfcPHA6cCwUIMQON/Sv3j/Fs7YfqvujH6IHqMe2p8Kz0/PhV/dsBdwbX' +
  'ClgO5BCZEmUTThOwEtERVRANDgsLCgf5Af37o/VU8Fnsiek76Nvo5erZ7Z/x3vUy+nL+9wKJB8ILBg97EQwTqhNTE44SOxEzDzwM' +
  'jwjdA0T+xffV8UTt3OnG54vnIumw61bvsfNz+Ob8SwHdBT8Kww1qEHoSahNkE8ASwxEOEIANKwrgBZsAafod9PDuDOtf6DjnIuh+' +
  '6uTtOPI59zX8AAGeBQgK7w2yEIsSjxOGE5MSQRFuD88MaglXBaQAD/tF9X7wneyt6RzocegL6trs1fC29bv6jf9WBBYJKQ1LEL4S' +
  'OhSYFOcTshLFEOoNWAo3BnsBF/yE9uLxIu47627pSumL6v7sjPAv9QD6of5FA+UHAAwhD54RZBMIFIITfRLKEB8OpQqmBhsCDf3C' +
  '90jzqO/Q7PLqlOpt62LtgPCt9Gv5Ef5yAgAHAAvxDTQQ6BGGEikSMhGkDz8NLwrFBhUD6f55+qj2bfOh8HXufu2U7YLumfDY85X3' +
  'Y/th/1ADBwc6Cs4M4g4bEEAQuA+PDn8M7Qk5B0EECgGQ/e/51/Y69BDyufA88KrwGvJw9Er3dfp5/WQAbgMwBmMIOgqeCzEMBQwz' +
  'C7EJqAdeBesCiABq/mr8Q/o++MT2iPWY9Ff0w/SB9d32ofjH+u/8JP8kAQwDwwQmBiMHsQdpB4cG6AUgBdADXAL6ANj/6P7C/cz8' +
  'X/y++/z6DPtm+3L7bvvU+2T8z/yJ/Wz+JP/C/3oAQQEDAncCpgLvAhYDEAMLA8ACUALgAa0BawFOAU4BAQG7AN8ABwEZASUBIwEr' +
  'AToBNAHxALQAkADDAAEBKQFpAX4BnQHwARsCMwJQAjcCOAJuAqECoQKtAtUCDQNJA3kDrgO4A48DhgN/A0UDBQPqAtcCkAJVAlUC' +
  'RwJMAlQCUgJ6AoQCjwLQAisDdAOTA6gDuwPYA78DkgN6AyQD0QKzAm8CNAI0AhoCFAI8AlMCcAKkAikDngMDBIkEDAV7BeEFYAb3' +
  'BmAHfwegB68HXgcSB70GfQbEBV8FtwQGBfMD8AQmA7oGlALUDCwNagQZCMEGIQqTA6MKyQhfBpoEWQJXCfEKywgwBJQGqARUA8z9' +
  'LALfAY7+5/7X/uIA5/wg/Un+CAF8/+r8Fv6J/y7/VwDHAS0A7wH0/Ab7SPvV/sb6XQRhBmsCnP8pACAC7/m89XD5tvpf8knxzfie' +
  '/Fv2UfccAUcB5/qp+UUC4ADk+cD4uf4Z/kP5Vfjw/g/8hPfy+AD9p/uY9k74g/xi+Arzu/aE/MT4T/V1+OT5y/cQ9gz6z/pi+KP3' +
  'Yfuo+673l/ku+1z7bvfM+DL6rfc49rv4NPmc9WX2mPk2+lr5b/iK+Wf6uvhv+ej64vlP+T35d/p++v340/hz+9n8lvxW+bX5d/f1' +
  '+EX57fjw91T5LPkb+ZP4Pfnw+i/4wPhf+i/8ufj/93j5bfsW+934pvk3/Gj8lfvI+hH7MfvR+zb7wPop/Ab+6P7m/Nr6Pfs7/HH9' +
  'e/zJ+zT6c/l2+6z8rv20/9kAbwF6/4b9Y/6FAN3/Gf6u+zn+TQHCAcf+0/5PAl0EsgKb/tf+3QDfAlH/CPzC/ZYDXggCAwL9L//Q' +
  'B1UKFwLB+jX8MAa/CLsA+/im/sYJiAuJAdv50v3+BWUJ2QOz+877HwGYBTsDqP9S/7ICqAdxB5ED1/6p/1gEfwcbBIv+TPxp/3YF' +
  '1AaiBBADXAMoBboDYgHk/p0CAwV2BdAChv3v/SACDAZBBCUBkgDJA8cEBwJw/+//oAP6BMkEsQI1AV0ACwGIAlIDsQQaBHEDJgHI' +
  '/qz+ywCKAuED2wM4A7MA8v6F/msAvQMeBm4GGQPA/QD7Qv35AlMHwQYDAej8lf2OAaoEhwI0/hL/FAPSBcYDJ/4J/L7/1AasCRgF' +
  'ivwE+sj+EgbWBzIEz/8Z/68BvAImAKD9lP9jBcMH/QPu/QD9TQFmBd0FSgRbAsoANgDIAF0CgAQuBfYD2wL0AX0C0wITAlQBfgGT' +
  'A0QFYQSyAZL/vQBpBHsGzgWLA4cCfAL3ApUDhQNOA9gDOARLBCQD6wHSAQEC4AJ/BCYFrQS+Al8BxQGMA6QEgwQ1Aq4AjAAbAt4C' +
  'ZgM+A/ECNQPZA7wEkAPyAdv/PAFrBM8GRQUQAXT9uv05AXwFRAf6BFkAav1F/t8BzgQpBQADi/+b/fb/DASiBv4E0gDF/fD9/gCz' +
  'BIgFgQIl/uP7Sv0/AvcFOwbCAUn9s/tp/m4CAgT2ArQAof6+/Q7+Bf95ALYBzwCN/p/85vyd/gIBkQFcAPv94Pzw/az/6f8r/tb8' +
  'mP1t/40AMwAV/+P+P/9y/5j+Df3R+z78p/3d/mP/B/8a/g39r/xg/Tv/pAAqALX9CvtR+9b9oACmAAv+//rX+nv8Uf4p//7+Q/48' +
  '/Rj8GfzJ/YMASwKNAZ/+kfva+pv8J/9sALH/Wf5n/U/9Zf3M/R7+R/7+/bv9Nv1F/Zn9wP6b/8j/CP+a/sn+aAC/Ae8BFwDG/Sf8' +
  'OvyH/Wr+Fv76/Kj77/rq+vn79v3E/ykA6f5I/R/9L/8uApkEEAUvBJ8CygAi/yL+CP5l/tD9qPvw+Db3Gfis+lf9V/4//jL+EP/4' +
  'AKYDTgYNCIYI3wc4BkkE9wIHAtQAlv7F+zH5ofdn9g/1UfQT9Xv4fP0UA9oG0AidCEwIsQiSCrQM2g0JDDEHOAHb/FX7W/sp+xX5' +
  'zvWw8uXxG/TV+Aj/YAUzCjAMHgviCMYHmwnuDEkPVw6ACpUETf+e+4/6PPqh+SH32/Pt8DXx5PQz/N4DeQp5Dd4N3Qv1CdAILAq2' +
  'DA4PSA4oCucDSv6A+i35Y/ix9qnz+vAR8Mvyo/h1AOYHCQ2ODuQMxwmNB6YHKAonDYYOlAzzB8kBx/zh+Uz5d/ht9qXyZO+d7jry' +
  'rvnSAs8KOQ9OD9YLewc6BZ0G3wrlDvsP0wwJB/UAu/zJ+iz6VPgL9Ajvd+yX7jz1W/5KB0wNFQ/6DLoIMAW3BHsHjgutDnAOFAsn' +
  'BpcBUv5L/JP6g/dP8iXtB+tT7oD29AAXCi0PcQ8rDKIHkQSrBNEHNQwQD1QOTQouBQIBnP4a/Sj7/faN8PLqu+m37nb4mwMvDPUP' +
  '0Q7vCpQGFgSxBA8IYAwyD38O0gpPBpwCEwDE/aH6WPVw7nHpS+lM72z5cwSKDPEPlg6aCnUGYwRcBa8IRwzhDY8MHwmSBcsCjQDQ' +
  '/dn5qfNw7PfniemH8Qb9qAcVDlQP6Qw3CWkGdgW/BkIJwAukDGcLrwjYBRsDWQDk/Hf49/Ea66Xnb+r98kv+RgjcDZYOGAzzCMoG' +
  'XwY7BxcJygp1C1sKEwieBQwDPwCG/GT3DPAa6ZfmzOp79Ov/AQliDWANDQusCC0H+waRB8IIkAmcCYEIIQdmBRMD+f/J++P1Ae5p' +
  '5wvmfeuo9asAiwj/C9MLdwoQCQUIdgdjB+gHQAgZCC0HRQYABQED6v9/+0P1Se0158/mDu1L95kBVAjeCnEKpQkzCUQJIAn4CJ0I' +
  'QAifB+4GVgZBBSUDzf8E+0z0K+z05tXnM++k+QUDVQjICZcJxwmJCt4KYQqLCb4IGgiiBzEHugadBXEDyf/E+rnzGOz/5zrqN/Id' +
  '/OwD3gfxCHAJkQrPC0EMkAtuCksJewjZB4QHAAeRBfgCDP/K+UryKeuY6JvsO/VH/nsEPAdJCI4JYQvQDPkM2Qt5CgkJIQhKB94G' +
  'BAZfBJ8Bgf269+Xv5elC6Rbv5ffF/x0E5wUKB1MJwws6DbUMTQuvCX8Idgd2BrQFbwR9AmD//vqJ9APtsOhW6m/x7fl6AJ8DCQWq' +
  'Bn0J1wuwDHgL1wk4CFQHSgZvBTwEsAJUANP83/e18NPpv+ci7DL0cvvu/wUC7APEBvMJxAu/CzsKwgh5B58GhQV0BMoC4ABY/qr6' +
  'EfV07TXolOi97lr2Q/xj/3YBQgTuB+UK/QtbCzIKCgnvB58GGwWiA8cB4P+t/Nr3mfCY6VvnaevY8mT5cv3Q/3ACOQYdCkYMQwwd' +
  'CxMK7Ai2BwoGSwRXAnQAPv6p+u/0Iu3X50zoMe5P9bb66/15AO8DJAiAC4EM0AsWC64KwAkmCK8FHAO7AB3/aPz7977wjekQ5+3q' +
  '/vHE92n7E/7RAXcGnQpVDEUMeAt+C+cKiAngBmoEvwG6/3T94Pmg8+DrkOcZ6RLv+PQ5+Tf8tv8qBMQIhwszDEYMjQxMDKEKdgjy' +
  'BZsDTgE8/6b7afYv71jpN+ga7KLx2/Vm+Wf9gAJOB/IKFQzYDIsNHg6uDCkKKAcNBeUClAD+/DP4w/GR673oeurZ7g7zPPf8+xYB' +
  '6AWeCTgMwA38DmUPLA7gC2wJSwfABLwBMv6U+RD0fe3O6djpIe3/8DL18vn3/goExggbDF4O6g/dEBIQAw6zCwQJAAZVAsD+UPo8' +
  '9f/u1urx6T7sV+9S80P4jP2mAmYHJQv3DY4PGxHBEDQPygxRChsHgQO5//b6jfUo7+7qkOm16kXt4vAQ9iL7pwB4BTAKgg13EB0S' +
  'FhJ8ECoOpwtiCIYEBwCz+nH1qO8e6wrp2OnF66bu1/OH+U3/OgTRCCMNahCsEgcTABKkD/sMNwnoBGYAYPvP9Y3vSutP6TfpReoX' +
  '7SvydvfP/H4CvQcxDL8PYxK/E+8SaBEdDkgK0AU4AdP7FfaJ8MLrQekb6CnpSOug78D0X/ocAMgFqAoHD4wSdBQuFHUSxg8zDLwH' +
  '3AJO/Zb3svGk7H/pBeg06Kfpru0n8u73zf2LAz0J5Q3GETAUrhVoFKoRQA6MCQkETv7g+Dvz7u2W6ovoMuho6Y/sePB69Zj7WQGo' +
  'BswK3g+dEpEUgBS0EjgP7QrdBWcA8Pro9cfwSezL6r/p6OmU68Hv2/OI+Hn9FwMiCM0MbRBWEyAU9xI7EPkMhQhqAzj/p/rt9abx' +
  'ee/97aHtse508ZH08/bx+rD/IwNMB1AM5A0SD1QPAQ7gC8UIhgW/AYn9S/tE+Dv1AfRb8/PyofOh9UP3F/pZ/KL/jAIHBaoHKQj8' +
  'CSIJpgnUCA0GBQRuAU7/h/zN+0D5lvhU+Av4nvcE+FH6ofqC/ML+5QCvAakCbgS5BGgF5gW9BIQDvwIEAjn/lf7o/sf8ifxG/U/7' +
  'ffst/DL8Gf1B/8X/8ABYAS4CswKeA68DpgNkA9sCRQOPAFoCXwA1/lX+zv9O/eH+Bv+I/lf/v/8NAFQAPwJBARkB5QIRApMB8QJW' +
  'A/oAfgOoAgIBKQKFARb/UAGyAOj+tP/OAJf+RP9yAmn/4ADXASYBxQD6A64ByAF7A+YA1QEEAz0AmgE2AbD/pwGQAJD//AGq//H/' +
  'DQFtAeb+3AFhAAkBqAFJAqcCeQKyAtQAVAJrAYgAFwJGANj/0P9gAK7+q/9FACn/AAC2AO7/A//LAo//bQAOAsAB4ABqAn8BmACK' +
  'AeIAev/m/7sAv/3EAMH+HP8VAHn/dv7+/wIAyv6FAR0BCQDQAOYB9v/2AXEAIwGx/1b/JP/q/5L97v8J/2QAaP7d/z8Ad/2iAA3/' +
  'e/7n/1D/Df/fAH3/p/+7/83/iP/R/+n+aAER/+b/F/8H/4T/kf7b/1H/Sf4T/+3/uPw6ABL/Av/K/8QAv/4q/xEB8P55AB//DQAc' +
  'AMD9yf+N/8n+xP7jAJ3+KQDuAHf+I/+kAPn84v+2/rv+TP6sABb+KgBPAOb/tgAIACUALv9XAeP+kf/j/hoAVP4sAIb/Lf+r/+P+' +
  'Gf4xAAv+pv7S/9f/qP5VAYcAG//nAIb/DQCQAM3+agCHAFD+Cv8qAIj9aP8H/0T/h/0rAHn9fgDR/rsAvf/w/8kA+v8EANv/2wHt' +
  '/jAAXwDe/gf/Ov8O/jj+AgAJ/jv/pwDO/uD/KwHW/1r+NgE3/ioAGgHc/+b+lgKq/kEAdgC+/lYAXADZ/vH+0v9h/fsAKv8V/1MB' +
  '7/5n/xEBMP9eAY4AfgBEAiYAdQBtAFgARv6LAQz/kP9eAFcAo/7KAK//Bv/0AHEBEf6sAvj/FwDMABUC7v4aAtMAMP/KAkkAlf8U' +
  'ARoAxv3aAff+i//cAScAN/87AS7/rACiAHcBOQAvASgB8gCcABoBnwEM/2wBAf8GAAEAbABN/5kAngDfAAIA+wFL/60AVgGC/4EA' +
  '3wLq/nUBagJd/vcAggC+/pIB8wCG/oQDEwD6/rABzv+A/gAE7v3JAHoCnP4GAVYCNv6wAAsC5P2LAS8BRv9pATICe/0nAswANv+4' +
  'Afr/4v8SAcf/rv/+Ab7+ogFBAaD+qgJTADn/YgKZ/03/KgIPAIb+LgIX/psAXgGb/w4BGwJg/90AFgHD/n0BVQHS/ssBHAB8/wsA' +
  'sQCp/vQBqP/cANQAUwFTAIwAHQEGAKAAHQGr/6L/iQHc/pP/AwLD/g8AMgEKAO7+6QMk/aYBUgD//hoBygEt/xYBcgHu/jQBI/+3' +
  '/uoAhv82AD4AWf8fAFQAfQAQAB8Alf4mAYb+3QAxACsA5v8IAW3/rf/GAG3/CQBeAPX+Nf6tAZX9lgAmAOT+7wDq/wAANgCE/0b/' +
  'EwDv/2YAy/7l/3r/Qf8oAfH+pwCgAGb+xP74ACj9ywGi/vb+5AAZ/7P+wwE2//n/NQEL/pEApwAz/nwAjgGj/TQCA//G/uD/7f/Y' +
  '/nQBFwBq/6YB0f8NAFsBgP+nAP7+i/+y/6z/yABhAGz/dQLh/hICowFP/0kAPgE1/hoD2/7r/wwBJ//7/hUCc/9JAm4Brv/RAYr/' +
  'aAHJAWoAIwEhAPUADwFYADsAqAGR/xcBjwFe/qcDPgDu/zMCJACh/yUCTP9HASIBiP96AD8BQf7kAlL/GAG+AZQADwEcAd7/jwGe' +
  'ABQBugAy/7sBiv9fAcMAQgEbAcYB4f7oAmH/cQFuAAQC/P16BDL+LgBhAyj9NwGZAfj+kAAnA0b86wQ0/4QAtgHsAPT/7gFq/oIA' +
  'pAAi/zkCRABKAA0C0P5BAY8BVv64AV8A5/1ZAir9MQExAJT/UgFfAAEAcgAO/+r/NQFI/jQB2/60/iIBe/5m/50Bh/y4AWsAyv2E' +
  'Amj/Cv4sA+r8DAFy/8/+av+uAYj8KwN5/QcABAAl/nf/v//1/fIAkv5A/5L/x/8q/94AEP9Q/zcB2v3p//n+bv/Q/p7/Wf6K/w0A' +
  'of/1/lIBIP7f/8T/Ov7tAMH+z/7d/+f+Jv9HANL9hgHR/r3/Vf/x//H9igDD/g8ADwD+/yv/VgDe/sL+dQFY/r//oADl/akAlABt' +
  '/kcBuv+r/fwB0/yG/5D/Mv4k/k0A3P1PAFMA3P4ZAuv/kQJHAFwCTgB9AQb/m/8w/Vz+k/uH/AD84PvH/Nf9if4KAN8BLwLxBQgF' +
  'tQVLB/0DOwSjAuz9L/+y+V/2o/Yv8mPyG/XN8/n4AP7Q/1kJiAu3D4UTwxGVEsAONgmbBST9e/ZN76Tpledf5j3nIOvN8LL3iQBA' +
  'CV8RlxepG3IcnBzIGHUUTgw+BeL6+fGx6H3mit9q5OPiWemz8fT3HgSBDO4T1hmvHSYbHB0VFocTmg29BTUAwvfE72zpzefC4uno' +
  'Xucn7qH0bvrJAzEMaxBGFkcYOBZGFxISuxC5DDMJPANZ/7T3yu857qDnv+gu6yHoqPLV8vL8RQSWC6QO5BZDE/EWXRU8ERMSAw18' +
  'CPIEJ/0l9T/uE+oa5Bbpa+Xs63vxyfWwAH4IEg1GFM8WzBN6GKwQjRDdD4UIhggmAXP64vM46ozpc+Pd6K/m0e6V8q/6lwIbC0QP' +
  'ZRTTFdkS5RRWDg8PjwwyCbcGCQGA+VHxR+kv5z/jkOkt6P7x7PQ6/i8F8AwXEJQTVBQNEF8ScQu/DZQLawluBzwBjPpu8KHpx+UO' +
  '497o4eir8sz2pP9KBrMOiw8KFaISsxDREBYLsAwvCz4JwgchAdf6Au8D6QPkJuMF6eHquPS8+IMBxgZJDjIPLRKhEBQOBA5oCosL' +
  'TAtTC9YJVwWy/lnzTek25WPhgOhF65XzGPlQAHgFaw3KDiIRthCrDfkN8gtkDOcMoAyPCnwHyv+S9l/pL+Wv3/vlgup48oz4ff4S' +
  'BFwKBA8IEDIR7g1uDTwLlgxHCwcO0wpECkYDTvzs7pXmOOIg4VnqP+729577sQJkBosNfA2aD5kNgwzeCzkMkwx2DfsNCAw+Ca8B' +
  'ZfgS6kXkfN8r5GrrhPKL+cr9FwOzBwsNUQ5LD7kNwQxfDDMNng2+DiwO4gvRB3cAM/Ue6LHiut5k5ZjsqfSh+u/+ggNwCEENXQ5A' +
  'D1wNNQ2lDHsOtQ7ZD2oOygs+B3P/8PP25pPh794t5hruqPZ7+5//9QIbCCwMvQ24DaMM5QszDOENmQ7RD+0OhAybCBsBDfZY6Sfi' +
  '4d9M5IPtm/SY+jb98QDvBPwJAwwrDVsMowzZDPIO2A+rEDIQcQ6QCtkEf/pa7grj/t984U3qb/Lj+Lj7uP4KAlMH5wrFDEIMQgxs' +
  'DNQNXg9bEKsQ7A9hDbMJtQET9rDo6eCn37HkO+6I9Rz6uPuC/jUCQgfUCV8LJAuiDA0NRQ/GDxkRrRDzEFAOegr3AEL1k+fR4Jzf' +
  'XOXX7aD0d/iN+lH9IwGqBZYInAphCyYNPA4TEJkQqRFwEesRvg+BC6UCXffl6X7het+/47vrzfIi97T5EfxP/14DyQaQCbILJA6/' +
  'D9MQ7BAPEX0RYxJKEfwNGgdE/ZHwxeXM4DHhseZI7arySfYp+Wr8YwCcBP0HwAp5DakPIxGlEcgR4xFJElUSzhBhDLkEgvqL7kLl' +
  'UeGH4rPnRu378X/13vg7/BsA9gNKB5sK3A2jEE4S1hLeEhkTpxObE58R+AzDBSj8zfB856niXOK45Sjqr+6O8nn2UfqN/o8CWQb2' +
  'CdUNyBCSEvIS7BIJE3YTrBOsElkPXgkkARn3lOxi5SriV+Ot5g/rG+8g89b2w/rQ/gQD+wb0CrsOaxHLEjsTWhO3EyAU+hOLEqsO' +
  '8wen/4f1hOue5Nfh6uIC5hzqKO5w8or2q/r4/lMDiAevC4UPKBJcE4UTxxMjFFYU2hMOEn0ObAjdADD39exV5crhQeIk5T3pQO12' +
  '8ZH1w/ne/UsCqgYNCxUP5REPExkTDhNNE7MTFBRME8MQnAuKBL37JvEX6JfiOOHm4mvmb+qY7tDyH/eT+xgApgT5CA4NPxDwEYgS' +
  'yBJyEyIUuRR0FK0S4g7GCEUBOPjU7b3lteG34Q/ku+eE67rvDfSB+K789gBCBYUJow3YEHYSFxNrEwgUXRSTFOYTuRGyDekH1AD6' +
  '9+DtAubj4XXhU+O+5sLqTe/b80r4YvyoAOoEWQlaDUsQ3RHNEnsTHBRSFF0UyBMXEtYO1AlFA177QPFA6L/iOeE14iflBumc7Uzy' +
  '5Pbn+sP+3AJYB6gLVA+GEaESIxOME6ITrBOlEwkT4hAfDYEHqQDI96vt5+UR4qjhOuNn5lfq/e7J8074RvwvAFAEpQiHDH4PGBEB' +
  'EqESORN8E8UTyRMQE8IQ6wxaB40Al/d07cPlD+KB4djiz+XF6ZTul/Mt+BL87v8iBKQIlQyODwYRuxEdEpQStBL8Ej4TFRNOEf8N' +
  '8wiFAkL6EvBV53/iPeHv4R7kwOd47JXxg/bt+vn+HgOVB5sLew75D60Q/xCGEQoSpRJYE7cT6xJqEEUMZwYd/wX2z+tR5Bfh8OD/' +
  '4YrkwehA7sHzovjH/OIAKgWQCRcNNQ8DEGUQsxA4EZsRRRIpE98TLROdEEkMawb+/or16epF4+Pfut/L4Hzj3ufT7bvz7Pgs/WYB' +
  'ywVaCq0NVA+2DxYQZhC4EAER3REtE1gUEhTeEeYNewhAAXL4tO2W5Mnf/97Z38PheeU6663xVffc+/3/ewT+CKEMig4GDy8Phw/j' +
  'D00QMBHIEogUYRVdFG4RzwxvBlT+TvRW6XfhIt4z3lvf7eGN5hjtlfMM+XD9tgE4BpoKsA3TDrUOtQ4qD88PlxAAEgEU2xVhFvEU' +
  'lRGQDOAFff2L87vo5uCa3bXd996c4WLmGe2z8yP5iv3XATsGagpvDasOiw5zDuYOrA+mEDASTBQtFrsWhxWVEsgNSwc0/931SOsy' +
  '4nTdddxx3Y/fDOSk6tvx0Pes/NYA2QSkCNkLrw0NDg8OiQ5YD2AQyRHqEwEWTRceF0YVchGeCywEiPu/8RvnA9+E24vbPt1a4L/l' +
  'w+zS84r5UP56AnIG+AnADCYORw4ZDlQOHA9gEEwSrhS6FskXXBc2FQURzQoGAyb6I/CY5eHdj9qy2qPcFuDP5RbtWvRG+hj/KwME' +
  'B2UK+QwsDh0Oyw3pDYsOzA/XEWgUvhYXGOkX+BUNEhUMXQSi+yry+udG37La2tmY27be+OMu6+3yjvm6/hoD9wZZCs0MEA7qDUIN' +
  'Ag1nDZEOhBA+Ex8WQhjqGKoXYRQ5D0gIFwAb92TthOO83BPam9r33PPgL+fD7gD22vurANMEcghiC2MNNg7lDXUNVg3FDfoOMBEW' +
  'FK0WEhjhFwsWQhK3DIkFnP1I9XfsheNH3a7aH9ud3cPhC+iC79H2z/yIASkFQggHCwoN1Q2FDUANZw0XDkgPORHKEx4WbRdFF1cV' +
  'gRFNDNQFnv4u95DvlefJ4D7dvNx43q3hm+YN7evz5Pmf/nsCvgWkCDELGA3yDT0Orw6JD3kQmRE3EwoVLBYPFk4UXhHfDBIIUQEP' +
  '/GDzi/pnAT3/fQCr/zoA2P8aAO//CgD6/wMA/v8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=';

const connectivityWavBytes = (): Uint8Array => decodeBase64(CONNECTIVITY_WAV_BASE64);

const encodeBase64 = (bytes: Uint8Array): string => {
  let binary = '';
  const chunkSize = 0x8000;
  for (let offset = 0; offset < bytes.length; offset += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(offset, offset + chunkSize));
  }
  return btoa(binary);
};

const appendMultipartField = (name: string, value: string): Uint8Array =>
  concatBytes(
    textBytes(`--${CONNECTIVITY_BOUNDARY}\r\n`),
    textBytes(`Content-Disposition: form-data; name="${name}"\r\n\r\n`),
    textBytes(`${value}\r\n`)
  );

const parseMultipartFieldsText = (value: string): Record<string, string> =>
  Object.fromEntries(
    value
      .split(/[\n,]+/)
      .map((line) => line.trim())
      .filter(Boolean)
      .flatMap((line) => {
        const separator = line.indexOf('=');
        if (separator <= 0) return [];
        const name = line.slice(0, separator).trim();
        if (!name) return [];
        return [[name, line.slice(separator + 1)]];
      })
  );

const appendMultipartFile = (
  name: string,
  filename: string,
  contentType: string,
  content: Uint8Array
): Uint8Array =>
  concatBytes(
    textBytes(`--${CONNECTIVITY_BOUNDARY}\r\n`),
    textBytes(
      `Content-Disposition: form-data; name="${name}"; filename="${filename}"\r\nContent-Type: ${contentType}\r\n\r\n`
    ),
    content,
    textBytes('\r\n')
  );

const operationNeedsFile = (
  kind: MediaKind,
  operation: MediaConnectivityRequestInput['operation']
): boolean => {
  const capability = (operation?.capability ?? operation?.name ?? '').trim().toLowerCase();
  const path = operation?.path?.trim().toLowerCase() ?? '';
  if (kind === 'image') {
    return (
      ['edit', 'upscale', 'super-resolution', 'remove-background'].includes(capability) ||
      path.includes('/edits') ||
      path.includes('upscale') ||
      path.includes('super-resolution') ||
      path.includes('remove-background')
    );
  }
  if (kind === 'video') return capability === 'image-to-video' || path.includes('image-to-video');
  return (
    capability === 'clone' ||
    capability === 'voice-convert' ||
    capability === 'transcribe' ||
    path.includes('convert') ||
    path.includes('transcriptions') ||
    path.includes('speech-to-text')
  );
};

const modelModeFor = (operation: MediaConnectivityRequestInput['operation']): MediaModelMode =>
  operation?.modelMode ?? 'optional';

const requestFormatFor = (
  operation: MediaConnectivityRequestInput['operation']
): MediaRequestFormat => operation?.requestFormat ?? 'json';

const buildFields = (
  kind: MediaKind,
  model: string,
  modelMode: MediaModelMode,
  operation: MediaConnectivityRequestInput['operation']
): Array<[string, string]> => {
  const fields: Array<[string, string]> = [];
  if (modelMode !== 'none' && model) fields.push(['model', model]);
  if (kind === 'image') {
    fields.push(['prompt', CONNECTIVITY_IMAGE_PROMPT], ['n', '1']);
  } else if (kind === 'video') {
    fields.push(['prompt', 'CPA connectivity test']);
  } else if (
    operation?.capability?.trim().toLowerCase() === 'transcribe' ||
    operation?.name?.trim().toLowerCase() === 'transcribe'
  ) {
    fields.push(['language', 'zh']);
  } else {
    fields.push(['input', 'CPA connectivity test'], ['voice', 'alloy']);
  }
  return fields;
};

export function buildMediaConnectivityRequest(
  input: MediaConnectivityRequestInput
): MediaConnectivityRequest {
  const operation = input.operation;
  const method = (operation?.method ?? 'POST').trim().toUpperCase() || 'POST';
  const requestFormat = requestFormatFor(operation);
  const modelMode = modelModeFor(operation);
  const model =
    modelMode === 'none' ? '' : (input.model ?? '').trim() || (operation?.model ?? '').trim();
  const headers: Record<string, string> = { ...(input.headers ?? {}) };
  const apiKey = input.apiKey?.trim() ?? '';
  if (apiKey) {
    const headerName = input.apiKeyHeader?.trim() || 'Authorization';
    if (!hasHeader(headers, headerName)) {
      const rawPrefix = input.apiKeyPrefix;
      const prefix =
        rawPrefix === undefined || rawPrefix.trim() === ''
          ? 'Bearer '
          : rawPrefix.trim() === '-'
            ? ''
            : `${rawPrefix.trim()} `;
      setHeader(headers, headerName, `${prefix}${apiKey}`);
    }
  }

  const rawPath = operation?.path?.trim() || defaultPathByKind[input.kind];
  const path = expandModelPath(rawPath, model);
  const pathUsesModel = rawPath.includes('{model}');
  const request: MediaConnectivityRequest = {
    method,
    url: joinPath(input.baseUrl, path),
    header: headers,
  };
  const fields = buildFields(input.kind, model, pathUsesModel ? 'none' : modelMode, operation);
  const canHaveBody = method !== 'GET' && method !== 'HEAD';

  if (requestFormat === 'json') {
    if (canHaveBody) {
      let payload: Record<string, unknown>;
      const customJSON = operation?.testRequest?.json?.trim() || operation?.testRequestJson?.trim();
      if (customJSON) {
        try {
          const parsed: unknown = JSON.parse(customJSON);
          payload =
            parsed && typeof parsed === 'object' && !Array.isArray(parsed)
              ? { ...(parsed as Record<string, unknown>) }
              : {};
        } catch {
          payload = {};
        }
      } else {
        payload = Object.fromEntries(fields);
        if (input.kind === 'image') payload.n = 1;
        if (
          (input.kind === 'image' || input.kind === 'video') &&
          operationNeedsFile(input.kind, operation)
        ) {
          payload.image = CONNECTIVITY_PNG_DATA_URL;
        }
      }
      if (modelMode !== 'none' && model && !pathUsesModel) {
        payload.model = model;
      }
      request.data = JSON.stringify(payload);
      setHeader(request.header, 'Content-Type', 'application/json');
    }
    return request;
  }

  if (requestFormat === 'binary') {
    if (canHaveBody) {
      request.dataBase64 = encodeBase64(textBytes('CPA media connectivity test'));
      setHeader(request.header, 'Content-Type', 'application/octet-stream');
    }
    return request;
  }

  if (canHaveBody) {
    const configuredMultipartFields = operation?.testRequest?.multipartFields ?? {};
    const formMultipartFields = operation?.testRequestMultipartFieldsText
      ? parseMultipartFieldsText(operation.testRequestMultipartFieldsText)
      : {};
    const customMultipartFields = Object.entries(
      Object.keys(configuredMultipartFields).length
        ? configuredMultipartFields
        : formMultipartFields
    ).map(([name, value]) => [name, String(value)] as [string, string]);
    const multipartFields = new Map(customMultipartFields.length ? customMultipartFields : fields);
    if (modelMode !== 'none' && model && !pathUsesModel) {
      multipartFields.set('model', model);
    }
    const parts = Array.from(multipartFields, ([name, value]) => appendMultipartField(name, value));
    if (operationNeedsFile(input.kind, operation)) {
      const isAudio = input.kind === 'audio';
      const capability = (operation?.capability ?? operation?.name ?? '').trim().toLowerCase();
      const fileField = isAudio
        ? capability === 'transcribe' || capability === 'clone'
          ? 'file'
          : 'audio'
        : 'image';
      parts.push(
        appendMultipartFile(
          fileField,
          isAudio ? 'connectivity-test.wav' : 'connectivity-test.png',
          isAudio ? 'audio/wav' : 'image/png',
          isAudio ? connectivityWavBytes() : decodeBase64(CONNECTIVITY_PNG_BASE64)
        )
      );
    }
    const body = concatBytes(...parts, textBytes(`--${CONNECTIVITY_BOUNDARY}--\r\n`));
    request.dataBase64 = encodeBase64(body);
    setHeader(
      request.header,
      'Content-Type',
      `multipart/form-data; boundary=${CONNECTIVITY_BOUNDARY}`
    );
  }
  return request;
}

const normalizeOperationValue = (value: string | undefined): string =>
  (value ?? '').trim().toLowerCase().split('_').join('-');

const normalizedOperationKey = (operation: MediaConnectivityOperation): string =>
  normalizeOperationValue(operation.name) || normalizeOperationValue(operation.capability);

export const getMediaGatewayPath = (
  kind: MediaKind,
  operation: MediaConnectivityOperation
): string => {
  const key = normalizedOperationKey(operation);
  if (kind === 'image') {
    const routes: Record<string, string> = {
      generate: '/v1/images/generations',
      edit: '/v1/images/edits',
      upscale: '/v1/images/upscale',
      'super-resolution': '/v1/images/super-resolution',
      'remove-background': '/v1/images/remove-background',
    };
    if (routes[key]) return routes[key];
  }
  if (kind === 'video') {
    const routes: Record<string, string> = {
      'text-to-video': '/v1/videos/text-to-video',
      'image-to-video': '/v1/videos/image-to-video',
      'remove-watermark': '/v1/videos/remove-watermark',
    };
    if (routes[key]) return routes[key];
  }
  if (kind === 'audio') {
    const routes: Record<string, string> = {
      speech: '/v1/audio/speech',
      music: '/v1/audio/music',
      clone: '/v1/audio/clone',
      'voice-convert': '/v1/audio/voice-convert',
      transcribe: '/v1/audio/transcriptions',
    };
    if (routes[key]) return routes[key];
  }
  const operationName = (operation.name || operation.capability || 'operation').trim();
  return `/v1/media/${kind}/${encodeURIComponent(operationName)}`;
};

export interface MediaGatewayConnectivityRequestInput {
  kind: MediaKind;
  gatewayBaseUrl: string;
  gatewayApiKey: string;
  model?: string;
  operation: MediaConnectivityOperation;
}

export const buildMediaGatewayConnectivityRequest = (
  input: MediaGatewayConnectivityRequestInput
): MediaConnectivityRequest =>
  buildMediaConnectivityRequest({
    kind: input.kind,
    baseUrl: input.gatewayBaseUrl,
    model: input.model,
    operation: {
      ...input.operation,
      path: getMediaGatewayPath(input.kind, input.operation),
      model: undefined,
    },
    apiKey: input.gatewayApiKey,
    apiKeyHeader: 'Authorization',
    apiKeyPrefix: 'Bearer',
  });

const mediaErrorMessage = (value: unknown): string => {
  if (typeof value === 'string') return value.trim();
  if (!value || typeof value !== 'object' || Array.isArray(value)) return '';
  const record = value as Record<string, unknown>;
  if (typeof record.message === 'string') return record.message.trim();
  if (typeof record.detail === 'string') return record.detail.trim();
  return '';
};

const MEDIA_SUCCESS_CODES = new Set([
  '0',
  '200',
  '1000',
  '10000',
  'ok',
  'success',
  'succeeded',
  'completed',
]);
const MEDIA_FAILURE_STATUSES = new Set(['error', 'failed', 'failure', 'cancelled', 'canceled']);
const MEDIA_SUCCESS_STATUSES = new Set(['ok', 'success', 'succeeded', 'completed', 'done']);
const MEDIA_FAILURE_MESSAGE_PARTS = [
  'error',
  'invalid',
  'fail',
  'denied',
  'insufficient',
  'exceeded',
  'blocked',
  'unavailable',
  'not found',
  'too short',
  'credit',
  'balance',
];

const normalizedMediaCode = (value: unknown): string => {
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  if (typeof value === 'string') return value.trim().toLowerCase();
  return '';
};

const isMediaSuccessCode = (code: string): boolean => {
  if (MEDIA_SUCCESS_CODES.has(code)) return true;
  if (!/^\d+$/.test(code)) return false;
  const numeric = Number(code);
  return numeric >= 200 && numeric < 300;
};

const hasMediaResponsePayload = (record: Record<string, unknown>): boolean =>
  ['data', 'result', 'output', 'outputs', 'url', 'id', 'task_id'].some((key) => {
    const value = record[key];
    if (value === null || value === undefined || value === false || value === '') return false;
    if (Array.isArray(value)) return value.length > 0;
    if (typeof value === 'object') return Object.keys(value as Record<string, unknown>).length > 0;
    return true;
  });

export const getMediaConnectivityApplicationError = (
  body: unknown,
  bodyText = ''
): string | null => {
  if (!body || typeof body !== 'object' || Array.isArray(body)) return null;
  const record = body as Record<string, unknown>;
  const directError = mediaErrorMessage(record.error);
  const message =
    directError ||
    mediaErrorMessage(record) ||
    (typeof record.error === 'string' ? record.error.trim() : '') ||
    bodyText.trim();
  const status = typeof record.status === 'string' ? record.status.trim().toLowerCase() : '';
  const statusFailed = MEDIA_FAILURE_STATUSES.has(status);
  const statusSucceeded = MEDIA_SUCCESS_STATUSES.has(status);
  const code = normalizedMediaCode(record.code);
  const hasCode = code !== '';
  const explicitSuccess = record.success === true || record.ok === true || statusSucceeded;
  const hasPayload = hasMediaResponsePayload(record);
  const businessCodeFailed =
    hasCode && !isMediaSuccessCode(code) && !explicitSuccess && !hasPayload;
  const directErrorFailed = Boolean(directError) && !explicitSuccess && !hasPayload;
  const messageOnlyFailed =
    !hasCode &&
    !directError &&
    !explicitSuccess &&
    !hasPayload &&
    MEDIA_FAILURE_MESSAGE_PARTS.some((part) => message.toLowerCase().includes(part));
  if (
    record.success === false ||
    record.ok === false ||
    statusFailed ||
    directErrorFailed ||
    businessCodeFailed ||
    messageOnlyFailed
  ) {
    return message || `Media provider returned an application error${code ? ` (${code})` : ''}`;
  }
  return null;
};

const MEDIA_ERROR_PROBE_LIMIT_BYTES = 64 * 1024;

const readPossibleJSONResponse = async (
  response: Response
): Promise<{ body: unknown; text: string } | null> => {
  const contentType = response.headers.get('Content-Type')?.toLowerCase() ?? '';
  if (contentType.includes('json') || contentType.startsWith('text/')) {
    const text = (await response.text()).trim();
    if (!text) return null;
    try {
      return { body: JSON.parse(text), text };
    } catch {
      return { body: text, text };
    }
  }

  const reader = response.clone().body?.getReader();
  if (!reader) return null;
  const decoder = new TextDecoder();
  let text = '';
  let total = 0;
  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      if (!value?.length) continue;
      total += value.length;
      if (total > MEDIA_ERROR_PROBE_LIMIT_BYTES) return null;
      text += decoder.decode(value, { stream: true });
      const first = text.trimStart()[0];
      if (first && first !== '{' && first !== '[') return null;
    }
    text = (text + decoder.decode()).trim();
    if (!text) return null;
    try {
      return { body: JSON.parse(text), text };
    } catch {
      return null;
    }
  } finally {
    void reader.cancel().catch(() => {});
  }
};

export interface MediaGatewayConnectivityFetchOptions {
  fetchImpl?: typeof fetch;
  timeoutMs?: number;
}

export interface MediaGatewayConnectivityResult {
  statusCode: number;
}

export const requestMediaGatewayConnectivity = async (
  request: MediaConnectivityRequest,
  options: MediaGatewayConnectivityFetchOptions = {}
): Promise<MediaGatewayConnectivityResult> => {
  const fetchImpl = options.fetchImpl ?? fetch;
  const timeoutMs = options.timeoutMs ?? MEDIA_CONNECTIVITY_TIMEOUT_MS;
  const controller = timeoutMs > 0 ? new AbortController() : null;
  const timeout = controller
    ? globalThis.setTimeout(() => controller.abort(), timeoutMs)
    : undefined;
  const method = request.method.toUpperCase();
  const body =
    method === 'GET' || method === 'HEAD'
      ? undefined
      : request.dataBase64
        ? (decodeBase64(request.dataBase64).buffer as ArrayBuffer)
        : request.data;

  try {
    const response = await fetchImpl(request.url, {
      method,
      headers: request.header,
      body,
      signal: controller?.signal,
    });
    if (!response.ok) {
      const message = (await response.text()).trim().replace(/\s+/g, ' ').slice(0, 800);
      throw new Error(`HTTP ${response.status}${message ? `: ${message}` : ''}`);
    }
    const parsed = await readPossibleJSONResponse(response);
    if (parsed) {
      const applicationError = getMediaConnectivityApplicationError(parsed.body, parsed.text);
      if (applicationError) throw new Error(`HTTP ${response.status}: ${applicationError}`);
    }
    return { statusCode: response.status };
  } catch (error) {
    if (controller?.signal.aborted) {
      throw new Error(`Request timed out after ${timeoutMs}ms`);
    }
    throw error;
  } finally {
    if (timeout !== undefined) globalThis.clearTimeout(timeout);
  }
};
